In [1]:
%load_ext sql

In [2]:
%sql mysql+pymysql://root:**********@localhost:3306/md_water_services

'Connected: root@md_water_services'

In [13]:
%%sql
Select 
province_name,
employee_name,
position
FROM employee;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
56 rows affected.

[('Sokoto', 'Amara Jengo', 'Field Surveyor'),
 ('Kilimani', 'Bello Azibo', 'Field Surveyor'),
 ('Hawassa', 'Bakari Iniko', 'Field Surveyor'),
 ('Akatsi', 'Malachi Mavuso', 'Field Surveyor'),
 ('Akatsi', 'Cheche Buhle', 'Field Surveyor'),
 ('Kilimani', 'Zuriel Matembo', 'Field Surveyor'),
 ('Akatsi', 'Deka Osumare', 'Field Surveyor'),
 ('Kilimani', 'Lalitha Kaburi', 'Field Surveyor'),
 ('Hawassa', 'Enitan Zuri', 'Field Surveyor'),
 ('Amanzi', 'Farai Nia', 'Field Surveyor'),
 ('Hawassa', 'Gamba Shani', 'Field Surveyor'),
 ('Kilimani', 'Harith Nyota', 'Field Surveyor'),
 ('Sokoto', 'Isoke Amani', 'Field Surveyor'),
 ('Akatsi', 'Jengo Tumaini', 'Field Surveyor'),
 ('Amanzi', 'Kunto Asha', 'Field Surveyor'),
 ('Sokoto', 'Lesedi Kofi', 'Field Surveyor'),
 ('Hawassa', 'Makena Thabo', 'Field Surveyor'),
 ('Akatsi', 'Nia Furaha', 'Field Surveyor'),
 ('Akatsi', 'Ona Sefu', 'Field Surveyor'),
 ('Hawassa', 'Pili Zola', 'Field Surveyor'),
 ('Sokoto', 'Quibilah Akua', 'Field Surveyor'),
 ('Kilimani', 'Rudo Imani', 'Field Surveyor'),
 ('Amanzi', 'Sanaa Tendaji', 'Field Surveyor'),
 ('Hawassa', 'Thandiwe Kito', 'Field Surveyor'),
 ('Sokoto', 'Usafi Ayo', 'Field Surveyor'),
 ('Kilimani', 'Vuyisile Kwame', 'Field Surveyor'),
 ('Hawassa', 'Wambui Jabali', 'Field Surveyor'),
 ('Amanzi', 'Xola Uzuri', 'Field Surveyor'),
 ('Hawassa', 'Yewande Ebele', 'Field Surveyor'),
 ('Kilimani', 'Nadia Zalika', 'Project Manager'),
 ('Hawassa', 'Ayo Deka', 'UI/UX Designer'),
 ('Amanzi', 'Bahira Jamila', 'Front-end Developer'),
 ('Hawassa', 'Chidi Kunto', 'Data Analyst'),
 ('Sokoto', 'Dalila Lesedi', 'Data Analyst'),
 ('Hawassa', 'Eshe Makena', 'Human Resources Specialist'),
 ('Kilimani', 'Faridah Khalida', 'Pioneer'),
 ('Akatsi', 'Gavivi Ona', 'Financial Analyst'),
 ('Hawassa', 'Hasani Pili', 'Deputy Project Manager'),
 ('Hawassa', 'Iniko Quibilah', 'Financial Manager'),
 ('Amanzi', 'Jengo Rudo', 'Civil Engineer'),
 ('Kilimani', 'Kofi Sanaa', 'Creative Designer'),
 ('Hawassa', 'Lulu Thandiwe', 'Team Leader'),
 ('Sokoto', 'Makena Usafi', 'Quality Assurance Analyst'),
 ('Sokoto', 'Nia Vuyisile', 'Civil Engineer'),
 ('Hawassa', 'Ona Wambui', 'Public Relations Specialist'),
 ('Kilimani', 'Pili Xola', 'Civil Engineer'),
 ('Kilimani', 'Quibilah Yewande', 'Supervisor'),
 ('Akatsi', 'Rudo Zalika', 'Field Engineer'),
 ('Akatsi', 'Sanaa Ayo', 'Data Scientist'),
 ('Akatsi', 'Thabo Akida', 'Engineering Department Head'),
 ('Akatsi', 'Usafi Bahir', 'Analytical Chemist'),
 ('Akatsi', 'Vuyisile Ghadir', 'Micro Biologist'),
 ('Kilimani', 'Wambui Hadiya', 'Compliance Officer'),
 ('Akatsi', 'Xola Inaya', 'Field Engineer'),
 ('Amanzi', 'Yewande Jengo', 'Construction Manager'),
 ('Sokoto', 'Zuri Kofi', 'Graphic Designer')]

In [19]:
%%sql
SELECT
assigned_employee_id,
town_name,
position
FROM employee
GROUP BY position;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
(pymysql.err.OperationalError) (1055, "Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'md_water_services.employee.assigned_employee_id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by")
[SQL: SELECT
assigned_employee_id,
town_name,
position
FROM employee
GROUP BY position;]
(Background on this error at: http://sqlalche.me/e/14/e3q8)

In [ ]:
/* 
TASK: 
Cleaning the data;
Bring up the employee table. It has info on all of the workers, but the email addresses have not been added. 
Luckily the emails for our department are easy: 
first_name.last_name@ndogowater.gov.Update it.
*/

In [173]:
%%sql
SELECT
    *
FROM
employee;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
56 rows affected.

[(0, 'Amara Jengo', '+99637993287', 'amara . jengo@ndogowater.gov', '36 Pwani Mchangani Road', 'Sokoto', 'Ilanga', 'Field Surveyor'),
 (1, 'Bello Azibo', '+99643864786', 'bello . azibo@ndogowater.gov', '129 Ziwa La Kioo Road', 'Kilimani', 'Rural', 'Field Surveyor'),
 (2, 'Bakari Iniko', '+99222599041', 'bakari . iniko@ndogowater.gov', '18 Mlima Tazama Avenue', 'Hawassa', 'Rural', 'Field Surveyor'),
 (3, 'Malachi Mavuso', '+99945849900', 'malachi . mavuso@ndogowater.gov', '100 Mogadishu Road', 'Akatsi', 'Lusaka', 'Field Surveyor'),
 (4, 'Cheche Buhle', '+99381679640', 'cheche . buhle@ndogowater.gov', '1 Savanna Street', 'Akatsi', 'Rural', 'Field Surveyor'),
 (5, 'Zuriel Matembo', '+99034075111', 'zuriel . matembo@ndogowater.gov', '26 Bahari Ya Faraja Road', 'Kilimani', 'Rural', 'Field Surveyor'),
 (6, 'Deka Osumare', '+99379364631', 'deka . osumare@ndogowater.gov', '104 Kenyatta Street', 'Akatsi', 'Rural', 'Field Surveyor'),
 (7, 'Lalitha Kaburi', '+99681623240', 'lalitha . kaburi@ndogowater.gov', '145 Sungura Amanpour Road', 'Kilimani', 'Rural', 'Field Surveyor'),
 (8, 'Enitan Zuri', '+99248509202', 'enitan . zuri@ndogowater.gov', '117 Kampala Road', 'Hawassa', 'Zanzibar', 'Field Surveyor'),
 (10, 'Farai Nia', '+99570082739', 'farai . nia@ndogowater.gov', '33 Angélique Kidjo Avenue', 'Amanzi', 'Dahabu', 'Field Surveyor'),
 (12, 'Gamba Shani', '+99438283153', 'gamba . shani@ndogowater.gov', '38 Mlima Tazama Avenue', 'Hawassa', 'Rural', 'Field Surveyor'),
 (14, 'Harith Nyota', '+99917230124', 'harith . nyota@ndogowater.gov', '42 Malabo Drive', 'Kilimani', 'Rural', 'Field Surveyor'),
 (16, 'Isoke Amani', '+99313603182', 'isoke . amani@ndogowater.gov', '55 Fennec Way', 'Sokoto', 'Rural', 'Field Surveyor'),
 (18, 'Jengo Tumaini', '+99820596465', 'jengo . tumaini@ndogowater.gov', '17 Port Harcourt Boulevard', 'Akatsi', 'Kintampo', 'Field Surveyor'),
 (20, 'Kunto Asha', '+99176320477', 'kunto . asha@ndogowater.gov', '30 Nyoka Achebe Street', 'Amanzi', 'Dahabu', 'Field Surveyor'),
 (22, 'Lesedi Kofi', '+99611183730', 'lesedi . kofi@ndogowater.gov', '52 Moroni Avenue', 'Sokoto', 'Rural', 'Field Surveyor'),
 (24, 'Makena Thabo', '+99690308755', 'makena . thabo@ndogowater.gov', '81 Rhodes Street', 'Hawassa', 'Rural', 'Field Surveyor'),
 (26, 'Nia Furaha', '+99522694997', 'nia . furaha@ndogowater.gov', '51 Addis Ababa Road', 'Akatsi', 'Harare', 'Field Surveyor'),
 (28, 'Ona Sefu', '+99797494944', 'ona . sefu@ndogowater.gov', '67 Wimbi Dira Avenue', 'Akatsi', 'Harare', 'Field Surveyor'),
 (30, 'Pili Zola', '+99822478933', 'pili . zola@ndogowater.gov', '46 Stone Town Street', 'Hawassa', 'Zanzibar', 'Field Surveyor'),
 (32, 'Quibilah Akua', '+99533195846', 'quibilah . akua@ndogowater.gov', '77 Kinshasa Boulevard', 'Sokoto', 'Rural', 'Field Surveyor'),
 (34, 'Rudo Imani', '+99046972648', 'rudo . imani@ndogowater.gov', '15 Lake Malawi Avenue', 'Kilimani', 'Ilanga', 'Field Surveyor'),
 (36, 'Sanaa Tendaji', '+99477692836', 'sanaa . tendaji@ndogowater.gov', '88 Elephantine Boulevard', 'Amanzi', 'Dahabu', 'Field Surveyor'),
 (38, 'Thandiwe Kito', '+99895654233', 'thandiwe . kito@ndogowater.gov', '106 Dakar Road', 'Hawassa', 'Zanzibar', 'Field Surveyor'),
 (40, 'Usafi Ayo', '+99613194771', 'usafi . ayo@ndogowater.gov', '76 Kenyatta Street', 'Sokoto', 'Rural', 'Field Surveyor'),
 (42, 'Vuyisile Kwame', '+99489752164', 'vuyisile . kwame@ndogowater.gov', '1 Zambezi Way', 'Kilimani', 'Rural', 'Field Surveyor'),
 (44, 'Wambui Jabali', '+99269319001', 'wambui . jabali@ndogowater.gov', '31 Mandela Road', 'Hawassa', 'Rural', 'Field Surveyor'),
 (46, 'Xola Uzuri', '+99239172440', 'xola . uzuri@ndogowater.gov', '50 Enkare Narok Avenue', 'Amanzi', 'Dahabu', 'Field Surveyor'),
 (48, 'Yewande Ebele', '+99239164858', 'yewande . ebele@ndogowater.gov', '119 Moroni Avenue', 'Hawassa', 'Rural', 'Field Surveyor'),
 (49, 'Nadia Zalika', '+99578401238', 'nadia . zalika@ndogowater.gov', '26 Bahari Ya Faraja Road', 'Kilimani', 'Rural', 'Project Manager'),
 (50, 'Ayo Deka', '+99345162378', 'ayo . deka@ndogowater.gov', '18 Mlima Tazama Avenue', 'Hawassa', 'Rural', 'UI/UX Designer'),
 (52, 'Bahira Jamila', '+99239271483', 'bahira . jamila@ndogowater.gov', '30 Nyoka Achebe Street', 'Amanzi', 'Dahabu', 'Front-end Developer'),
 (53, 'Chidi Kunto', '+99738251476', 'chidi . kunto@ndogowater.gov', '146 Okapi Road', 'Hawassa', 'Yaounde', 'Data Analyst'),
 (54, 'Dalila Lesedi', '+99471523698', 'dalila . lesedi@ndogowater.gov', '18 Casablanca Road', 'Sokoto', 'Rural', 'Data Analyst'),
 (56, 'Eshe Makena', '+99381254763', 'eshe . makena@ndogowater.gov', '45 Umqombothi Avenue', 'Hawassa', 'Serowe', 'Human Resources Specialist'),
 (58, 'Faridah Khalida', '+99142537684', 'faridah . khalida@ndogowater.gov', '176 Port Said Street', 'Kilimani', 'Harare', 'Pioneer'),
 (62, 'Gavivi Ona', '+99924513876', 'gavivi . ona@ndogowater.gov', '51 Addis Ababa Road', 'Akatsi', 'Harare', 'Financial Analyst'),
 (64, 'Hasani Pili', '+99568247135', 'hasani . pili@ndogowater.gov', '33 Afro Beat Road', 'Hawassa', 'Serowe', 'Deputy Project Manager'),
 (68, 'Iniko Quibilah', '+99735681472', 'iniko . quibilah@ndogowater.gov', '93 Afro Beat Road', 'Hawassa', 'Serowe', 'Financial Manager'),
 (71, 'Jengo Rudo', '+99317854629', 'jengo . rudo@ndogowater.gov', '33 Angélique Kidjo Avenue', 'Amanzi', 'Dahabu', 'Civil Engineer'),
 (73, 'Kofi Sanaa', '+99874512369', 'kofi . sanaa@ndogowater.gov', '42 Malabo Drive', 'Kilimani', 'Rural', 'Creative Designer'),
 (75, 'Lulu Thandiwe', '+99127436598', 'lulu . thandiwe@ndogowater.gov', '117 Kampala Road', 'Hawassa', 'Zanzibar', 'Team Leader'),
 (79, 'Makena Usafi', '+99583124796', 'makena . usafi@ndogowater.gov', '55 Fennec Way', 'Sokoto', 'Rural', 'Quality Assurance Analyst'),
 (81, 'Nia Vuyisile', '+99273841596', 'nia . vuyisile@ndogowater.gov', '52 Moroni Avenue', 'Sokoto', 'Rural', 'Civil Engineer'),
 (83, 'Ona Wambui', '+99968217435', 'ona . wambui@ndogowater.gov', '81 Rhodes Street', 'Hawassa', 'Rural', 'Public Relations Specialist'),
 (87, 'Pili Xola', '+99682314579', 'pili . xola@ndogowater.gov', '31 Samora Machel Road', 'Kilimani', 'Harare', 'Civil Engineer'),
 (89, 'Quibilah Yewande', '+99721534698', 'quibilah . yewande@ndogowater.gov', '110 Nyerere Road', 'Kilimani', 'Rural', 'Supervisor'),
 (93, 'Rudo Zalika', '+99578123469', 'rudo . zalika@ndogowater.gov', '7 Dakar Drive', 'Akatsi', 'Lusaka', 'Field Engineer'),
 (94, 'Sanaa Ayo', '+99375418692', 'sanaa . ayo@ndogowater.gov', '172 Fisi Nkrumah Street', 'Akatsi', 'Rural', 'Data Scientist'),
 (96, 'Thabo Akida', '+99178325649', 'thabo . akida@ndogowater.gov', '24 Okonjo-Iweala Street', 'Akatsi', 'Lusaka', 'Engineering Department Head'),
 (98, 'Usafi Bahir', '+99234156789', 'usafi . bahir@ndogowater.gov', '1 Savanna Street', 'Akatsi', 'Rural', 'Analytical Chemist'),
 (102, 'Vuyisile Ghadir', '+99712584936', 'vuyisile . ghadir@ndogowater.gov', '104 Kenyatta Street', 'Akatsi', 'Rural', 'Micro Biologist'),
 (104, 'Wambui Hadiya', '+99634157892', 'wambui . hadiya@ndogowater.gov', '145 Sungura Amanpour Road', 'Kilimani', 'Rural', 'Compliance Officer'),
 (105, 'Xola Inaya', '+99231569847', 'xola . inaya@ndogowater.gov', '100 Mogadishu Road', 'Akatsi', 'Lusaka', 'Field Engineer'),
 (108, 'Yewande Jengo', '+99123456978', 'yewande . jengo@ndogowater.gov', '25 Selassie Drive', 'Amanzi', 'Rural', 'Construction Manager'),
 (110, 'Zuri Kofi', '+99412356789', 'zuri . kofi@ndogowater.gov', '36 Pwani Mchangani Road', 'Sokoto', 'Ilanga', 'Graphic Designer')]

In [182]:
%%sql
SELECT
    COUNT(*) AS number_of_employees
FROM employee
WHERE town_name IN (SELECT 'Harare' UNION SELECT 'Kilimani');

 * mysql+pymysql://root:***@localhost:3306/md_water_services
1 rows affected.

[(5,)]

In [19]:
%%sql
SELECT
    REPLACE(employee_name, ' ', ' . ') AS Rep_emp_name
FROM 
employee;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
56 rows affected.

[('Amara . Jengo',),
 ('Bello . Azibo',),
 ('Bakari . Iniko',),
 ('Malachi . Mavuso',),
 ('Cheche . Buhle',),
 ('Zuriel . Matembo',),
 ('Deka . Osumare',),
 ('Lalitha . Kaburi',),
 ('Enitan . Zuri',),
 ('Farai . Nia',),
 ('Gamba . Shani',),
 ('Harith . Nyota',),
 ('Isoke . Amani',),
 ('Jengo . Tumaini',),
 ('Kunto . Asha',),
 ('Lesedi . Kofi',),
 ('Makena . Thabo',),
 ('Nia . Furaha',),
 ('Ona . Sefu',),
 ('Pili . Zola',),
 ('Quibilah . Akua',),
 ('Rudo . Imani',),
 ('Sanaa . Tendaji',),
 ('Thandiwe . Kito',),
 ('Usafi . Ayo',),
 ('Vuyisile . Kwame',),
 ('Wambui . Jabali',),
 ('Xola . Uzuri',),
 ('Yewande . Ebele',),
 ('Nadia . Zalika',),
 ('Ayo . Deka',),
 ('Bahira . Jamila',),
 ('Chidi . Kunto',),
 ('Dalila . Lesedi',),
 ('Eshe . Makena',),
 ('Faridah . Khalida',),
 ('Gavivi . Ona',),
 ('Hasani . Pili',),
 ('Iniko . Quibilah',),
 ('Jengo . Rudo',),
 ('Kofi . Sanaa',),
 ('Lulu . Thandiwe',),
 ('Makena . Usafi',),
 ('Nia . Vuyisile',),
 ('Ona . Wambui',),
 ('Pili . Xola',),
 ('Quibilah . Yewande',),
 ('Rudo . Zalika',),
 ('Sanaa . Ayo',),
 ('Thabo . Akida',),
 ('Usafi . Bahir',),
 ('Vuyisile . Ghadir',),
 ('Wambui . Hadiya',),
 ('Xola . Inaya',),
 ('Yewande . Jengo',),
 ('Zuri . Kofi',)]

In [8]:
%%sql
SELECT
    LOWER(REPLACE(employee_name, ' ', ' . ')) AS Rep_emp_name
FROM 
employee;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
56 rows affected.

[('amara . jengo',),
 ('bello . azibo',),
 ('bakari . iniko',),
 ('malachi . mavuso',),
 ('cheche . buhle',),
 ('zuriel . matembo',),
 ('deka . osumare',),
 ('lalitha . kaburi',),
 ('enitan . zuri',),
 ('farai . nia',),
 ('gamba . shani',),
 ('harith . nyota',),
 ('isoke . amani',),
 ('jengo . tumaini',),
 ('kunto . asha',),
 ('lesedi . kofi',),
 ('makena . thabo',),
 ('nia . furaha',),
 ('ona . sefu',),
 ('pili . zola',),
 ('quibilah . akua',),
 ('rudo . imani',),
 ('sanaa . tendaji',),
 ('thandiwe . kito',),
 ('usafi . ayo',),
 ('vuyisile . kwame',),
 ('wambui . jabali',),
 ('xola . uzuri',),
 ('yewande . ebele',),
 ('nadia . zalika',),
 ('ayo . deka',),
 ('bahira . jamila',),
 ('chidi . kunto',),
 ('dalila . lesedi',),
 ('eshe . makena',),
 ('faridah . khalida',),
 ('gavivi . ona',),
 ('hasani . pili',),
 ('iniko . quibilah',),
 ('jengo . rudo',),
 ('kofi . sanaa',),
 ('lulu . thandiwe',),
 ('makena . usafi',),
 ('nia . vuyisile',),
 ('ona . wambui',),
 ('pili . xola',),
 ('quibilah . yewande',),
 ('rudo . zalika',),
 ('sanaa . ayo',),
 ('thabo . akida',),
 ('usafi . bahir',),
 ('vuyisile . ghadir',),
 ('wambui . hadiya',),
 ('xola . inaya',),
 ('yewande . jengo',),
 ('zuri . kofi',)]

In [20]:
%%sql
SELECT
CONCAT(
    LOWER(REPLACE(employee_name, ' ', ' . ')), '@ndogowater.gov') AS new_email
FROM 
employee;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
56 rows affected.

[('amara . jengo@ndogowater.gov',),
 ('bello . azibo@ndogowater.gov',),
 ('bakari . iniko@ndogowater.gov',),
 ('malachi . mavuso@ndogowater.gov',),
 ('cheche . buhle@ndogowater.gov',),
 ('zuriel . matembo@ndogowater.gov',),
 ('deka . osumare@ndogowater.gov',),
 ('lalitha . kaburi@ndogowater.gov',),
 ('enitan . zuri@ndogowater.gov',),
 ('farai . nia@ndogowater.gov',),
 ('gamba . shani@ndogowater.gov',),
 ('harith . nyota@ndogowater.gov',),
 ('isoke . amani@ndogowater.gov',),
 ('jengo . tumaini@ndogowater.gov',),
 ('kunto . asha@ndogowater.gov',),
 ('lesedi . kofi@ndogowater.gov',),
 ('makena . thabo@ndogowater.gov',),
 ('nia . furaha@ndogowater.gov',),
 ('ona . sefu@ndogowater.gov',),
 ('pili . zola@ndogowater.gov',),
 ('quibilah . akua@ndogowater.gov',),
 ('rudo . imani@ndogowater.gov',),
 ('sanaa . tendaji@ndogowater.gov',),
 ('thandiwe . kito@ndogowater.gov',),
 ('usafi . ayo@ndogowater.gov',),
 ('vuyisile . kwame@ndogowater.gov',),
 ('wambui . jabali@ndogowater.gov',),
 ('xola . uzuri@ndogowater.gov',),
 ('yewande . ebele@ndogowater.gov',),
 ('nadia . zalika@ndogowater.gov',),
 ('ayo . deka@ndogowater.gov',),
 ('bahira . jamila@ndogowater.gov',),
 ('chidi . kunto@ndogowater.gov',),
 ('dalila . lesedi@ndogowater.gov',),
 ('eshe . makena@ndogowater.gov',),
 ('faridah . khalida@ndogowater.gov',),
 ('gavivi . ona@ndogowater.gov',),
 ('hasani . pili@ndogowater.gov',),
 ('iniko . quibilah@ndogowater.gov',),
 ('jengo . rudo@ndogowater.gov',),
 ('kofi . sanaa@ndogowater.gov',),
 ('lulu . thandiwe@ndogowater.gov',),
 ('makena . usafi@ndogowater.gov',),
 ('nia . vuyisile@ndogowater.gov',),
 ('ona . wambui@ndogowater.gov',),
 ('pili . xola@ndogowater.gov',),
 ('quibilah . yewande@ndogowater.gov',),
 ('rudo . zalika@ndogowater.gov',),
 ('sanaa . ayo@ndogowater.gov',),
 ('thabo . akida@ndogowater.gov',),
 ('usafi . bahir@ndogowater.gov',),
 ('vuyisile . ghadir@ndogowater.gov',),
 ('wambui . hadiya@ndogowater.gov',),
 ('xola . inaya@ndogowater.gov',),
 ('yewande . jengo@ndogowater.gov',),
 ('zuri . kofi@ndogowater.gov',)]

In [ ]:
-- Update the employee with the above new email

In [25]:
%%sql 
UPDATE employee
SET email = CONCAT(
    LOWER(REPLACE(employee_name, ' ', ' . ')), '@ndogowater.gov');

 * mysql+pymysql://root:***@localhost:3306/md_water_services
56 rows affected.

ResourceClosedError: This result object does not return rows. It has been closed automatically.

In [13]:
%%sql
SELECT
LENGTH (phone_number)
FROM 
employee;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
56 rows affected.

[(13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,),
 (13,)]

In [ ]:
/* The phone number ought to be 12 in length but I have 13,
so it means that there either a space or extra digit. in this case; it is  an extra space. 
use the TRIM function to remove the space*/

In [31]:
%%sql
SELECT
    TRIM(phone_number)
FROM
    employee;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
56 rows affected.

[('+99637993287',),
 ('+99643864786',),
 ('+99222599041',),
 ('+99945849900',),
 ('+99381679640',),
 ('+99034075111',),
 ('+99379364631',),
 ('+99681623240',),
 ('+99248509202',),
 ('+99570082739',),
 ('+99438283153',),
 ('+99917230124',),
 ('+99313603182',),
 ('+99820596465',),
 ('+99176320477',),
 ('+99611183730',),
 ('+99690308755',),
 ('+99522694997',),
 ('+99797494944',),
 ('+99822478933',),
 ('+99533195846',),
 ('+99046972648',),
 ('+99477692836',),
 ('+99895654233',),
 ('+99613194771',),
 ('+99489752164',),
 ('+99269319001',),
 ('+99239172440',),
 ('+99239164858',),
 ('+99578401238',),
 ('+99345162378',),
 ('+99239271483',),
 ('+99738251476',),
 ('+99471523698',),
 ('+99381254763',),
 ('+99142537684',),
 ('+99924513876',),
 ('+99568247135',),
 ('+99735681472',),
 ('+99317854629',),
 ('+99874512369',),
 ('+99127436598',),
 ('+99583124796',),
 ('+99273841596',),
 ('+99968217435',),
 ('+99682314579',),
 ('+99721534698',),
 ('+99578123469',),
 ('+99375418692',),
 ('+99178325649',),
 ('+99234156789',),
 ('+99712584936',),
 ('+99634157892',),
 ('+99231569847',),
 ('+99123456978',),
 ('+99412356789',)]

In [172]:
%%sql
SELECT
TRIM('33 Angelique Kidjo Avenue  ')
FROM 
employee;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
56 rows affected.

[('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',),
 ('33 Angelique Kidjo Avenue',)]

In [33]:
%%sql
SELECT
    LENGTH(TRIM(phone_number))
FROM
    employee;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
56 rows affected.

[(12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,),
 (12,)]

In [34]:
%%sql
UPDATE employee
SET phone_number = TRIM(phone_number);

 * mysql+pymysql://root:***@localhost:3306/md_water_services
56 rows affected.

ResourceClosedError: This result object does not return rows. It has been closed automatically.

In [ ]:
--Use the employee table to count how many of THE employees live in each town.

In [39]:
%%sql
SELECT
   town_name,
COUNT(town_name)
FROM
employee
GROUP BY Town_name;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
9 rows affected.

[('Ilanga', 3),
 ('Rural', 29),
 ('Lusaka', 4),
 ('Zanzibar', 4),
 ('Dahabu', 6),
 ('Kintampo', 1),
 ('Harare', 5),
 ('Yaounde', 1),
 ('Serowe', 3)]

In [40]:
%%sql
SELECT DISTINCT
   town_name,
COUNT(town_name)
FROM
employee
GROUP BY Town_name;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
9 rows affected.

[('Ilanga', 3),
 ('Rural', 29),
 ('Lusaka', 4),
 ('Zanzibar', 4),
 ('Dahabu', 6),
 ('Kintampo', 1),
 ('Harare', 5),
 ('Yaounde', 1),
 ('Serowe', 3)]

In [ ]:
-- look up up the employee with the most visits to towns

In [7]:
%%sql
SELECT 
assigned_employee_id, COUNT(assigned_employee_id) AS num_of_visits
FROM visits
GROUP BY assigned_employee_id
ORDER BY num_of_visits DESC
LIMIT 3;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
3 rows affected.

[(1, 3708), (30, 3676), (34, 3539)]

In [160]:
%%sql
SELECT 
assigned_employee_id, COUNT(visit_count)
FROM visits
GROUP BY assigned_employee_id
ORDER BY COUNT(visit_count) DESC;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
29 rows affected.

[(1, 3708),
 (30, 3676),
 (34, 3539),
 (3, 3420),
 (10, 3407),
 (8, 3351),
 (5, 3284),
 (36, 3249),
 (48, 2933),
 (28, 2762),
 (12, 2561),
 (42, 2496),
 (40, 2344),
 (38, 2121),
 (2, 2033),
 (24, 2015),
 (32, 1852),
 (18, 1749),
 (46, 1632),
 (14, 1441),
 (7, 1259),
 (6, 1182),
 (4, 1136),
 (0, 1099),
 (16, 802),
 (26, 719),
 (44, 218),
 (22, 143),
 (20, 15)]

In [166]:
%%sql
SELECT employee_name, email, phone_number, assigned_employee_id
FROM employee
WHERE assigned_employee_id IN (1, 30, 34);

 * mysql+pymysql://root:***@localhost:3306/md_water_services
3 rows affected.

[('Bello Azibo', 'bello . azibo@ndogowater.gov', '+99643864786', 1),
 ('Pili Zola', 'pili . zola@ndogowater.gov', '+99822478933', 30),
 ('Rudo Imani', 'rudo . imani@ndogowater.gov', '+99046972648', 34)]

In [49]:
-- Identifying location of water sources in Maji Ndogo

SyntaxError: invalid syntax (3753186285.py, line 1)

In [51]:
%%sql
SELECT *
FROM location
LIMIT 100;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
100 rows affected.

[('AkHa00000', '2 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00001', '10 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00002', '9 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00003', '139 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00004', '17 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00005', '125 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00006', '98 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00007', '21 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00008', '11 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00009', '6 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00010', '28 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00011', '32 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00012', '52 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00013', '81 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00014', '142 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00015', '22 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00016', '55 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00017', '60 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00018', '120 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00019', '150 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00020', '16 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00021', '57 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00022', '132 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00023', '147 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00024', '116 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00025', '76 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00026', '82 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00027', '144 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00028', '72 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00029', '29 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00030', '121 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00031', '88 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00032', '75 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00033', '49 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00034', '95 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00035', '31 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00036', '54 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00037', '19 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00038', '37 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00039', '137 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00040', '63 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00041', '25 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00042', '86 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00043', '104 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00044', '138 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00045', '107 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00046', '140 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00047', '141 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00048', '102 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00049', '96 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00050', '45 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00051', '46 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00052', '48 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00053', '83 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00054', '5 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00055', '108 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00056', '110 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00057', '53 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00058', '12 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00059', '112 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00060', '85 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00061', '115 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00062', '103 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00063', '68 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00064', '38 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00065', '93 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00066', '56 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00067', '131 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00068', '130 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00069', '43 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00070', '51 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00071', '119 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00072', '79 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00073', '41 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00074', '59 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00075', '1 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00076', '126 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00077', '122 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00078', '134 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00079', '70 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00080', '148 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00081', '145 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00082', '77 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00083', '50 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00084', '35 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00085', '47 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00086', '74 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00087', '124 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00088', '149 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00089', '65 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00090', '34 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00091', '106 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00092', '13 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00093', '100 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00094', '135 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00095', '113 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00096', '118 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00097', '67 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00098', '26 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban'),
 ('AkHa00099', '114 Addis Ababa Road', 'Akatsi', 'Harare', 'Urban')]

In [65]:
%%sql
SELECT 
     town_name,
    COUNT(town_name) AS record_per_town
FROM location
GROUP BY town_name
ORDER BY record_per_town DESC;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
25 rows affected.

[('Rural', 23740),
 ('Harare', 1650),
 ('Amina', 1090),
 ('Lusaka', 1070),
 ('Mrembo', 990),
 ('Asmara', 930),
 ('Dahabu', 930),
 ('Kintampo', 780),
 ('Ilanga', 780),
 ('Isiqalo', 770),
 ('Zuri', 750),
 ('Amara', 710),
 ('Majengo', 620),
 ('Pwani', 520),
 ('Kofi', 510),
 ('Serowe', 480),
 ('Bahari', 470),
 ('Marang', 460),
 ('Abidjan', 400),
 ('Bello', 400),
 ('Cheche', 370),
 ('Deka', 350),
 ('Djenne', 310),
 ('Zanzibar', 300),
 ('Yaounde', 270)]

In [64]:
%%sql
SELECT 
     province_name,
    COUNT(province_name) AS record_per_town
FROM location
GROUP BY province_name 
ORDER BY record_per_town DESC;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
5 rows affected.

[('Kilimani', 9510),
 ('Akatsi', 8940),
 ('Sokoto', 8220),
 ('Amanzi', 6950),
 ('Hawassa', 6030)]

In [ ]:
/* find a way to do the following:
1. Create a result set showing:
• province_name
• town_name
• An aggregated count of records for each town (consider naming this records_per_town).
• Ensure the data is grouped by both province_name and town_name.
2. Order the results primarily by province_name. Within each province, 
further sort the towns by their record counts in descending order.

*/

In [72]:
%%sql
SELECT
     town_name,
     province_name,
    COUNT(town_name) AS record_per_town,
    COUNT(province_name) AS record_per_province
FROM location
GROUP BY province_name,town_name 
ORDER BY province_name, record_per_town DESC, record_per_province DESC;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
31 rows affected.

[('Rural', 'Akatsi', 6290, 6290),
 ('Lusaka', 'Akatsi', 1070, 1070),
 ('Harare', 'Akatsi', 800, 800),
 ('Kintampo', 'Akatsi', 780, 780),
 ('Rural', 'Amanzi', 3100, 3100),
 ('Asmara', 'Amanzi', 930, 930),
 ('Dahabu', 'Amanzi', 930, 930),
 ('Amina', 'Amanzi', 670, 670),
 ('Pwani', 'Amanzi', 520, 520),
 ('Abidjan', 'Amanzi', 400, 400),
 ('Bello', 'Amanzi', 400, 400),
 ('Rural', 'Hawassa', 3900, 3900),
 ('Serowe', 'Hawassa', 480, 480),
 ('Amina', 'Hawassa', 420, 420),
 ('Deka', 'Hawassa', 350, 350),
 ('Djenne', 'Hawassa', 310, 310),
 ('Zanzibar', 'Hawassa', 300, 300),
 ('Yaounde', 'Hawassa', 270, 270),
 ('Rural', 'Kilimani', 5440, 5440),
 ('Mrembo', 'Kilimani', 990, 990),
 ('Harare', 'Kilimani', 850, 850),
 ('Isiqalo', 'Kilimani', 770, 770),
 ('Zuri', 'Kilimani', 750, 750),
 ('Amara', 'Kilimani', 710, 710),
 ('Rural', 'Sokoto', 5010, 5010),
 ('Ilanga', 'Sokoto', 780, 780),
 ('Majengo', 'Sokoto', 620, 620),
 ('Kofi', 'Sokoto', 510, 510),
 ('Bahari', 'Sokoto', 470, 470),
 ('Marang', 'Sokoto', 460, 460),
 ('Cheche', 'Sokoto', 370, 370)]

In [ ]:
--  number of records for each location type

In [75]:
%%sql
SELECT 
     location_type,
    COUNT(town_name) AS record_per_location_type
FROM location
GROUP BY location_type;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
2 rows affected.

[('Urban', 15910), ('Rural', 23740)]

In [ ]:
-- represent these value in percentage

In [81]:
%%sql
SELECT
     ROUND(23740 / (23740 + 15910)* 100);

 * mysql+pymysql://root:***@localhost:3306/md_water_services
1 rows affected.

[(Decimal('60'),)]

In [ ]:
/* Insights gained from the location table?
1. The entire country was properly canvassed, and the dataset represents the situation on the ground.
2. 60% of water sources are in rural communities across Maji Ndogo. This will help me make informed decisions and recommendation. */

In [ ]:
/* Dive into the different water_sources supply.
Aswer the following question as regard the water_sources:
1. How many people did I survey in total?
2. How many wells, taps and rivers are there?
3. How many people share particular types of water sources on average?
4. How many people are getting water from each type of source?
*/

In [82]:
%%sql
SELECT *
FROM water_source
LIMIT 100;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
100 rows affected.

[('AkHa00000224', 'tap_in_home', 956),
 ('AkHa00001224', 'tap_in_home_broken', 930),
 ('AkHa00002224', 'tap_in_home_broken', 486),
 ('AkHa00003224', 'well', 364),
 ('AkHa00004224', 'tap_in_home_broken', 942),
 ('AkHa00005224', 'tap_in_home', 736),
 ('AkHa00006224', 'tap_in_home', 882),
 ('AkHa00007224', 'tap_in_home', 554),
 ('AkHa00008224', 'well', 398),
 ('AkHa00009224', 'well', 346),
 ('AkHa00010224', 'well', 236),
 ('AkHa00011224', 'well', 168),
 ('AkHa00012224', 'well', 192),
 ('AkHa00013224', 'shared_tap', 2212),
 ('AkHa00014224', 'tap_in_home_broken', 574),
 ('AkHa00015224', 'tap_in_home', 862),
 ('AkHa00016224', 'well', 278),
 ('AkHa00017224', 'tap_in_home_broken', 414),
 ('AkHa00018224', 'well', 390),
 ('AkHa00019224', 'tap_in_home_broken', 320),
 ('AkHa00020224', 'well', 234),
 ('AkHa00021224', 'tap_in_home_broken', 330),
 ('AkHa00022224', 'well', 304),
 ('AkHa00023224', 'tap_in_home_broken', 954),
 ('AkHa00024224', 'well', 292),
 ('AkHa00025224', 'tap_in_home', 354),
 ('AkHa00026224', 'well', 388),
 ('AkHa00027224', 'well', 224),
 ('AkHa00028224', 'well', 306),
 ('AkHa00029224', 'tap_in_home_broken', 816),
 ('AkHa00030224', 'well', 366),
 ('AkHa00031224', 'well', 354),
 ('AkHa00032224', 'well', 382),
 ('AkHa00033224', 'well', 384),
 ('AkHa00034224', 'well', 210),
 ('AkHa00035224', 'tap_in_home_broken', 920),
 ('AkHa00036224', 'shared_tap', 3488),
 ('AkHa00037224', 'well', 348),
 ('AkHa00038224', 'well', 308),
 ('AkHa00039224', 'well', 252),
 ('AkHa00040224', 'tap_in_home_broken', 338),
 ('AkHa00041224', 'tap_in_home', 672),
 ('AkHa00042224', 'tap_in_home', 766),
 ('AkHa00043224', 'tap_in_home_broken', 364),
 ('AkHa00044224', 'well', 304),
 ('AkHa00045224', 'well', 370),
 ('AkHa00046224', 'well', 186),
 ('AkHa00047224', 'well', 324),
 ('AkHa00048224', 'well', 174),
 ('AkHa00049224', 'tap_in_home_broken', 892),
 ('AkHa00050224', 'tap_in_home_broken', 716),
 ('AkHa00051224', 'tap_in_home', 900),
 ('AkHa00052224', 'tap_in_home', 374),
 ('AkHa00053224', 'tap_in_home_broken', 748),
 ('AkHa00054224', 'well', 378),
 ('AkHa00055224', 'tap_in_home', 562),
 ('AkHa00056224', 'well', 328),
 ('AkHa00057224', 'tap_in_home_broken', 876),
 ('AkHa00058224', 'well', 290),
 ('AkHa00059224', 'well', 316),
 ('AkHa00060224', 'tap_in_home_broken', 376),
 ('AkHa00061224', 'tap_in_home', 908),
 ('AkHa00062224', 'tap_in_home_broken', 576),
 ('AkHa00063224', 'well', 306),
 ('AkHa00064224', 'tap_in_home_broken', 538),
 ('AkHa00065224', 'tap_in_home_broken', 874),
 ('AkHa00066224', 'tap_in_home', 722),
 ('AkHa00067224', 'well', 302),
 ('AkHa00068224', 'well', 264),
 ('AkHa00069224', 'well', 306),
 ('AkHa00070224', 'well', 390),
 ('AkHa00071224', 'well', 212),
 ('AkHa00072224', 'tap_in_home_broken', 816),
 ('AkHa00073224', 'well', 354),
 ('AkHa00074224', 'tap_in_home_broken', 322),
 ('AkHa00075224', 'tap_in_home_broken', 358),
 ('AkHa00076224', 'well', 298),
 ('AkHa00077224', 'well', 262),
 ('AkHa00078224', 'tap_in_home_broken', 612),
 ('AkHa00079224', 'tap_in_home', 332),
 ('AkHa00080224', 'tap_in_home', 880),
 ('AkHa00081224', 'well', 318),
 ('AkHa00082224', 'tap_in_home_broken', 322),
 ('AkHa00083224', 'tap_in_home_broken', 744),
 ('AkHa00084224', 'shared_tap', 322),
 ('AkHa00085224', 'well', 346),
 ('AkHa00086224', 'well', 206),
 ('AkHa00087224', 'well', 288),
 ('AkHa00088224', 'well', 354),
 ('AkHa00089224', 'well', 268),
 ('AkHa00090224', 'shared_tap', 308),
 ('AkHa00091224', 'well', 350),
 ('AkHa00092224', 'well', 166),
 ('AkHa00093224', 'well', 324),
 ('AkHa00094224', 'tap_in_home', 672),
 ('AkHa00095224', 'tap_in_home_broken', 654),
 ('AkHa00096224', 'well', 184),
 ('AkHa00097224', 'tap_in_home', 538),
 ('AkHa00098224', 'well', 390),
 ('AkHa00099224', 'tap_in_home', 306)]

In [99]:

%%sql
SELECT 
SUM(number_of_people_served) AS Total_people_served

FROM water_source;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
1 rows affected.

[(Decimal('27628140'),)]

In [101]:

%%sql
SELECT 
type_of_water_source,
COUNT(type_of_water_source) AS count_of_water_source

FROM water_source
GROUP BY type_of_water_source
ORDER BY count_of_water_source DESC;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
5 rows affected.

[('well', 17383),
 ('tap_in_home', 7265),
 ('tap_in_home_broken', 5856),
 ('shared_tap', 5767),
 ('river', 3379)]

In [107]:
%%sql
SELECT 
type_of_water_source,
ROUND(AVG(number_of_people_served)) AS Avg_number_of_people_served

FROM water_source
GROUP BY type_of_water_source
ORDER BY Avg_number_of_people_served DESC;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
5 rows affected.

[('shared_tap', Decimal('2071')),
 ('river', Decimal('699')),
 ('tap_in_home_broken', Decimal('649')),
 ('tap_in_home', Decimal('644')),
 ('well', Decimal('279'))]

In [112]:
%%sql
SELECT 
type_of_water_source,
ROUND(SUM(number_of_people_served)) AS Sum_number_of_people_served

FROM water_source
GROUP BY type_of_water_source
ORDER BY Sum_number_of_people_served DESC;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
5 rows affected.

[('shared_tap', Decimal('11945272')),
 ('well', Decimal('4841724')),
 ('tap_in_home', Decimal('4678880')),
 ('tap_in_home_broken', Decimal('3799720')),
 ('river', Decimal('2362544'))]

In [113]:
%%sql
SELECT type_of_water_source, 
ROUND(SUM(number_of_people_served)/
(SELECT SUM(number_of_people_served) FROM water_source)* 100) AS percentage_of_people_served 
FROM water_source
GROUP BY type_of_water_source
ORDER BY percentage_of_people_served DESC;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
5 rows affected.

[('shared_tap', Decimal('43')),
 ('well', Decimal('18')),
 ('tap_in_home', Decimal('17')),
 ('tap_in_home_broken', Decimal('14')),
 ('river', Decimal('9'))]

In [114]:
%%sql
SELECT 
SUM(number_of_people_served)* 100
FROM water_source;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
1 rows affected.

[(Decimal('2762814000'),)]

In [131]:
%%sql
SELECT 
type_of_water_source,
SUM(number_of_people_served) AS Sum_num_of_people_served,
RANK() OVER (ORDER BY Sum(number_of_people_served)) AS Ranking
FROM water_source
WHERE type_of_water_source != 'tap_in_home'
GROUP BY type_of_water_source;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
4 rows affected.

[('river', Decimal('2362544'), 1),
 ('tap_in_home_broken', Decimal('3799720'), 2),
 ('well', Decimal('4841724'), 3),
 ('shared_tap', Decimal('11945272'), 4)]

In [134]:
%%sql

SELECT source_id, 
type_of_water_source, 
(number_of_people_served) AS num_of_people_served, 
RANK() OVER (PARTITION BY type_of_water_source 
         ORDER BY number_of_people_served DESC) AS Priority_of_ranking
FROM water_source
WHERE type_of_water_source != "tap_in_home"
LIMIT 1000;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
1000 rows affected.

[('SoRu34798224', 'river', 998, 1),
 ('SoRu35837224', 'river', 998, 1),
 ('SoRu36238224', 'river', 998, 1),
 ('SoRu36791224', 'river', 998, 1),
 ('SoRu36880224', 'river', 998, 1),
 ('SoRu38142224', 'river', 998, 1),
 ('SoRu37756224', 'river', 998, 1),
 ('SoMa33775224', 'river', 998, 1),
 ('KiRu30353224', 'river', 998, 1),
 ('SoIl32972224', 'river', 998, 1),
 ('KiZu31236224', 'river', 998, 1),
 ('KiRu28591224', 'river', 998, 1),
 ('KiMr25030224', 'river', 998, 1),
 ('KiRu25603224', 'river', 996, 14),
 ('KiRu26027224', 'river', 996, 14),
 ('KiRu30532224', 'river', 996, 14),
 ('SoRu36229224', 'river', 996, 14),
 ('AkRu08053224', 'river', 996, 14),
 ('AmAb09070224', 'river', 996, 14),
 ('SoKo33179224', 'river', 994, 20),
 ('HaRu20469224', 'river', 994, 20),
 ('KiRu28404224', 'river', 994, 20),
 ('KiRu27661224', 'river', 994, 20),
 ('SoRu36506224', 'river', 994, 20),
 ('SoRu37912224', 'river', 994, 20),
 ('SoRu35192224', 'river', 992, 26),
 ('SoRu36076224', 'river', 992, 26),
 ('SoRu37032224', 'river', 992, 26),
 ('SoMa33620224', 'river', 992, 26),
 ('AkRu04142224', 'river', 992, 26),
 ('SoRu38498224', 'river', 992, 26),
 ('SoRu39029224', 'river', 992, 26),
 ('AmRu13795224', 'river', 992, 26),
 ('KiRu28002224', 'river', 992, 26),
 ('KiRu27266224', 'river', 992, 26),
 ('KiRu29844224', 'river', 992, 26),
 ('SoRu37904224', 'river', 990, 37),
 ('SoRu37158224', 'river', 990, 37),
 ('SoRu37004224', 'river', 990, 37),
 ('KiRu25651224', 'river', 990, 37),
 ('SoIl32652224', 'river', 990, 37),
 ('HaRu17065224', 'river', 990, 37),
 ('AkRu08333224', 'river', 990, 37),
 ('AkRu05337224', 'river', 988, 44),
 ('AkRu06935224', 'river', 988, 44),
 ('KiAm22552224', 'river', 988, 44),
 ('KiRu28398224', 'river', 988, 44),
 ('KiRu28604224', 'river', 988, 44),
 ('AmAs10139224', 'river', 988, 44),
 ('AmDa11775224', 'river', 988, 44),
 ('SoRu37223224', 'river', 988, 44),
 ('SoRu36894224', 'river', 988, 44),
 ('SoKo33302224', 'river', 988, 44),
 ('SoMa34112224', 'river', 988, 44),
 ('SoKo33275224', 'river', 988, 44),
 ('SoCh32068224', 'river', 988, 44),
 ('HaRu20007224', 'river', 988, 44),
 ('HaRu19708224', 'river', 986, 58),
 ('KiMr24403224', 'river', 986, 58),
 ('KiHa23332224', 'river', 986, 58),
 ('AkRu03607224', 'river', 986, 58),
 ('KiZu30757224', 'river', 986, 58),
 ('SoBa31824224', 'river', 986, 58),
 ('SoMa33961224', 'river', 986, 58),
 ('SoBa31788224', 'river', 986, 58),
 ('SoRu36044224', 'river', 986, 58),
 ('SoRu37968224', 'river', 986, 58),
 ('SoRu35464224', 'river', 986, 58),
 ('SoRu36871224', 'river', 986, 58),
 ('SoRu35151224', 'river', 986, 58),
 ('SoRu38054224', 'river', 984, 71),
 ('SoRu37388224', 'river', 984, 71),
 ('SoRu35074224', 'river', 984, 71),
 ('KiMr24365224', 'river', 984, 71),
 ('AmAm09565224', 'river', 984, 71),
 ('SoRu39564224', 'river', 984, 71),
 ('SoRu39120224', 'river', 984, 71),
 ('SoRu38884224', 'river', 984, 71),
 ('HaRu20269224', 'river', 984, 71),
 ('SoKo33516224', 'river', 984, 71),
 ('SoKo33278224', 'river', 984, 71),
 ('AmRu13767224', 'river', 984, 71),
 ('AmRu13651224', 'river', 982, 83),
 ('SoRu38692224', 'river', 982, 83),
 ('SoRu39206224', 'river', 982, 83),
 ('AkRu07053224', 'river', 982, 83),
 ('SoRu36666224', 'river', 982, 83),
 ('SoRu36065224', 'river', 982, 83),
 ('SoRu38006224', 'river', 982, 83),
 ('SoRu37046224', 'river', 982, 83),
 ('AmBe11055224', 'river', 982, 83),
 ('AmDa11856224', 'river', 982, 83),
 ('SoBa31517224', 'river', 982, 83),
 ('HaRu19782224', 'river', 982, 83),
 ('HaYa21524224', 'river', 982, 83),
 ('SoRu34875224', 'river', 980, 96),
 ('SoRu36036224', 'river', 980, 96),
 ('KiAm22020224', 'river', 980, 96),
 ('AmRu13667224', 'river', 980, 96),
 ('AkRu06243224', 'river', 980, 96),
 ('AkRu08369224', 'river', 980, 96),
 ('AkRu06666224', 'river', 980, 96),
 ('SoBa31654224', 'river', 980, 96),
 ('SoCh32266224', 'river', 978, 104),
 ('SoKo33083224', 'river', 978, 104),
 ('AmRu13901224', 'river', 978, 104),
 ('SoRu37536224', 'river', 978, 104),
 ('SoRu37761224', 'river', 978, 104),
 ('SoRu36311224', 'river', 978, 104),
 ('SoRu37881224', 'river', 978, 104),
 ('HaSe21297224', 'river', 978, 104),
 ('AkRu07584224', 'river', 978, 104),
 ('AkLu02389224', 'river', 978, 104),
 ('SoRu35432224', 'river', 976, 114),
 ('SoRu35138224', 'river', 976, 114),
 ('SoRu34768224', 'river', 976, 114),
 ('SoRu38330224', 'river', 976, 114),
 ('SoRu38656224', 'river', 976, 114),
 ('SoKo33088224', 'river', 976, 114),
 ('SoIl32579224', 'river', 976, 114),
 ('KiRu26676224', 'river', 976, 114),
 ('KiRu27230224', 'river', 976, 114),
 ('KiRu29190224', 'river', 976, 114),
 ('SoMa34058224', 'river', 974, 124),
 ('SoKo33219224', 'river', 974, 124),
 ('SoRu37979224', 'river', 974, 124),
 ('SoRu35923224', 'river', 974, 124),
 ('AkRu03965224', 'river', 974, 124),
 ('AkRu03873224', 'river', 974, 124),
 ('KiAm21994224', 'river', 974, 124),
 ('AmAs10470224', 'river', 974, 124),
 ('HaRu18403224', 'river', 974, 124),
 ('HaRu20520224', 'river', 972, 133),
 ('SoRu34806224', 'river', 972, 133),
 ('SoRu37076224', 'river', 972, 133),
 ('SoRu35947224', 'river', 972, 133),
 ('SoRu36917224', 'river', 972, 133),
 ('SoRu36863224', 'river', 972, 133),
 ('SoRu37694224', 'river', 972, 133),
 ('AkRu08293224', 'river', 972, 133),
 ('AkRu07502224', 'river', 972, 133),
 ('AkRu06569224', 'river', 972, 133),
 ('AkRu06043224', 'river', 970, 143),
 ('KiRu30136224', 'river', 970, 143),
 ('AmRu14920224', 'river', 970, 143),
 ('AkKi01306224', 'river', 970, 143),
 ('AkRu02775224', 'river', 970, 143),
 ('AkRu03884224', 'river', 970, 143),
 ('SoMa34437224', 'river', 970, 143),
 ('SoRu34819224', 'river', 970, 143),
 ('SoRu35690224', 'river', 970, 143),
 ('SoRu34993224', 'river', 968, 152),
 ('SoRu36714224', 'river', 968, 152),
 ('SoRu36309224', 'river', 968, 152),
 ('SoRu35887224', 'river', 968, 152),
 ('SoRu35259224', 'river', 968, 152),
 ('SoRu36662224', 'river', 968, 152),
 ('AmRu13923224', 'river', 968, 152),
 ('AmRu14344224', 'river', 968, 152),
 ('AmRu15534224', 'river', 968, 152),
 ('KiRu28921224', 'river', 968, 152),
 ('KiRu28032224', 'river', 968, 152),
 ('SoMa33905224', 'river', 968, 152),
 ('SoRu38735224', 'river', 968, 152),
 ('SoRu39301224', 'river', 968, 152),
 ('AkRu03867224', 'river', 968, 152),
 ('AkRu04499224', 'river', 968, 152),
 ('AkRu03484224', 'river', 966, 168),
 ('SoMa33938224', 'river', 966, 168),
 ('KiZu30842224', 'river', 966, 168),
 ('SoRu35401224', 'river', 966, 168),
 ('SoRu34641224', 'river', 966, 168),
 ('SoRu37575224', 'river', 966, 168),
 ('SoRu37565224', 'river', 966, 168),
 ('HaRu20417224', 'river', 966, 168),
 ('HaSe21171224', 'river', 966, 168),
 ('AkRu05010224', 'river', 966, 168),
 ('AkRu04737224', 'river', 966, 168),
 ('KiRu29093224', 'river', 966, 168),
 ('KiRu27121224', 'river', 964, 180),
 ('KiRu27016224', 'river', 964, 180),
 ('SoRu36192224', 'river', 964, 180),
 ('SoRu36421224', 'river', 964, 180),
 ('SoRu36024224', 'river', 964, 180),
 ('SoCh31958224', 'river', 964, 180),
 ('AmRu13395224', 'river', 964, 180),
 ('SoRu39543224', 'river', 964, 180),
 ('SoRu39559224', 'river', 964, 180),
 ('KiRu25474224', 'river', 964, 180),
 ('KiRu25969224', 'river', 962, 190),
 ('SoBa31833224', 'river', 962, 190),
 ('SoMa33955224', 'river', 962, 190),
 ('SoRu36127224', 'river', 962, 190),
 ('SoRu34778224', 'river', 962, 190),
 ('HaRu18363224', 'river', 962, 190),
 ('HaRu18166224', 'river', 962, 190),
 ('SoRu39048224', 'river', 962, 190),
 ('SoRu39053224', 'river', 962, 190),
 ('SoRu38872224', 'river', 960, 199),
 ('SoRu38793224', 'river', 960, 199),
 ('SoRu38741224', 'river', 960, 199),
 ('SoRu38171224', 'river', 960, 199),
 ('SoRu36744224', 'river', 960, 199),
 ('SoRu35123224', 'river', 960, 199),
 ('SoRu37793224', 'river', 960, 199),
 ('SoRu35252224', 'river', 960, 199),
 ('SoRu35674224', 'river', 960, 199),
 ('KiRu29545224', 'river', 960, 199),
 ('KiRu28764224', 'river', 960, 199),
 ('KiRu28830224', 'river', 960, 199),
 ('AkRu05980224', 'river', 960, 199),
 ('KiAm22276224', 'river', 960, 199),
 ('AkRu04929224', 'river', 958, 213),
 ('AkRu07605224', 'river', 958, 213),
 ('SoRu37476224', 'river', 958, 213),
 ('SoRu35763224', 'river', 958, 213),
 ('AkRu03365224', 'river', 958, 213),
 ('AkRu03403224', 'river', 958, 213),
 ('AkRu03132224', 'river', 958, 213),
 ('SoRu38969224', 'river', 958, 213),
 ('KiRu27963224', 'river', 958, 213),
 ('KiRu28327224', 'river', 958, 213),
 ('KiRu30186224', 'river', 958, 213),
 ('SoKo33076224', 'river', 958, 213),
 ('SoMa34008224', 'river', 958, 213),
 ('SoIl32277224', 'river', 958, 213),
 ('KiZu31151224', 'river', 958, 213),
 ('HaRu19484224', 'river', 958, 213),
 ('HaRu17008224', 'river', 958, 213),
 ('AmRu14867224', 'river', 956, 230),
 ('SoRu37530224', 'river', 956, 230),
 ('KiRu25989224', 'river', 956, 230),
 ('KiIs23590224', 'river', 956, 230),
 ('SoRu38689224', 'river', 956, 230),
 ('SoRu39348224', 'river', 956, 230),
 ('HaRu18188224', 'river', 956, 230),
 ('HaRu19763224', 'river', 956, 230),
 ('AmBe11324224', 'river', 956, 230),
 ('KiZu30986224', 'river', 956, 230),
 ('SoMa33875224', 'river', 954, 240),
 ('KiAm22312224', 'river', 954, 240),
 ('KiRu25825224', 'river', 954, 240),
 ('HaRu17476224', 'river', 954, 240),
 ('AkRu05004224', 'river', 954, 240),
 ('AkRu07488224', 'river', 954, 240),
 ('SoRu36807224', 'river', 954, 240),
 ('SoRu37960224', 'river', 954, 240),
 ('SoRu37137224', 'river', 954, 240),
 ('SoRu37546224', 'river', 954, 240),
 ('SoRu35068224', 'river', 954, 240),
 ('AkRu04281224', 'river', 954, 240),
 ('AkRu03287224', 'river', 954, 240),
 ('SoRu39094224', 'river', 954, 240),
 ('SoRu35096224', 'river', 952, 254),
 ('SoRu37795224', 'river', 952, 254),
 ('SoRu37242224', 'river', 952, 254),
 ('SoMa34520224', 'river', 952, 254),
 ('KiAm22502224', 'river', 952, 254),
 ('KiAm22472224', 'river', 952, 254),
 ('KiRu28805224', 'river', 952, 254),
 ('SoCh31994224', 'river', 952, 254),
 ('KiZu31324224', 'river', 952, 254),
 ('KiRu30435224', 'river', 952, 254),
 ('SoBa31765224', 'river', 952, 254),
 ('AkRu06715224', 'river', 952, 254),
 ('AkRu05485224', 'river', 952, 254),
 ('AmDa12224224', 'river', 952, 254),
 ('AmAm09821224', 'river', 952, 254),
 ('AmAs10765224', 'river', 952, 254),
 ('HaSe20986224', 'river', 952, 254),
 ('HaRu20496224', 'river', 950, 271),
 ('SoBa31800224', 'river', 950, 271),
 ('SoIl32444224', 'river', 950, 271),
 ('SoMa34229224', 'river', 950, 271),
 ('KiRu25832224', 'river', 950, 271),
 ('KiRu25513224', 'river', 950, 271),
 ('SoRu39487224', 'river', 950, 271),
 ('SoRu37117224', 'river', 950, 271),
 ('AkLu02608224', 'river', 950, 271),
 ('AkRu04985224', 'river', 950, 271),
 ('SoRu38653224', 'river', 948, 281),
 ('SoRu38291224', 'river', 948, 281),
 ('KiMr24509224', 'river', 948, 281),
 ('SoCh32058224', 'river', 948, 281),
 ('AkLu02008224', 'river', 948, 281),
 ('AkRu08840224', 'river', 948, 281),
 ('SoRu36867224', 'river', 948, 281),
 ('SoRu36375224', 'river', 948, 281),
 ('SoRu38244224', 'river', 948, 281),
 ('SoRu37744224', 'river', 948, 281),
 ('SoRu37781224', 'river', 948, 281),
 ('SoRu37774224', 'river', 948, 281),
 ('SoRu35221224', 'river', 946, 293),
 ('KiRu25476224', 'river', 946, 293),
 ('SoRu38718224', 'river', 946, 293),
 ('SoRu38896224', 'river', 946, 293),
 ('AkRu06277224', 'river', 946, 293),
 ('KiRu27360224', 'river', 946, 293),
 ('KiRu28687224', 'river', 946, 293),
 ('AkRu08505224', 'river', 946, 293),
 ('AmDa11888224', 'river', 946, 293),
 ('SoKo33438224', 'river', 946, 293),
 ('SoMa33881224', 'river', 946, 293),
 ('SoIl32281224', 'river', 946, 293),
 ('KiZu30680224', 'river', 946, 293),
 ('SoBa31500224', 'river', 944, 306),
 ('SoMa34420224', 'river', 944, 306),
 ('SoKo33308224', 'river', 944, 306),
 ('AkRu08455224', 'river', 944, 306),
 ('HaRu18905224', 'river', 944, 306),
 ('HaRu19701224', 'river', 944, 306),
 ('SoMa34576224', 'river', 944, 306),
 ('SoRu36747224', 'river', 944, 306),
 ('SoRu39588224', 'river', 944, 306),
 ('HaDj16833224', 'river', 944, 306),
 ('AmDa11621224', 'river', 944, 306),
 ('AmRu12872224', 'river', 944, 306),
 ('AmPw12520224', 'river', 944, 306),
 ('KiRu28794224', 'river', 944, 306),
 ('AkRu04137224', 'river', 944, 306),
 ('SoRu39607224', 'river', 942, 321),
 ('KiAm22373224', 'river', 942, 321),
 ('SoKo33556224', 'river', 942, 321),
 ('SoRu34961224', 'river', 942, 321),
 ('KiRu29809224', 'river', 942, 321),
 ('KiRu28147224', 'river', 942, 321),
 ('KiRu28720224', 'river', 940, 327),
 ('KiRu29436224', 'river', 940, 327),
 ('SoMa34180224', 'river', 940, 327),
 ('KiZu30829224', 'river', 940, 327),
 ('SoCh32265224', 'river', 940, 327),
 ('SoRu39540224', 'river', 940, 327),
 ('SoRu38976224', 'river', 940, 327),
 ('AkRu07788224', 'river', 940, 327),
 ('KiIs23736224', 'river', 940, 327),
 ('KiIs24122224', 'river', 940, 327),
 ('HaRu19001224', 'river', 940, 327),
 ('SoMa34439224', 'river', 940, 327),
 ('SoRu37174224', 'river', 940, 327),
 ('SoRu34716224', 'river', 940, 327),
 ('SoRu35266224', 'river', 940, 327),
 ('AkRu08877224', 'river', 940, 327),
 ('SoBa31636224', 'river', 938, 343),
 ('KiRu28789224', 'river', 938, 343),
 ('SoRu38270224', 'river', 938, 343),
 ('SoRu37010224', 'river', 938, 343),
 ('SoRu36423224', 'river', 938, 343),
 ('AmRu15440224', 'river', 938, 343),
 ('HaRu19448224', 'river', 938, 343),
 ('AmAm09481224', 'river', 936, 350),
 ('SoKo33230224', 'river', 936, 350),
 ('AkRu06075224', 'river', 936, 350),
 ('AkRu05182224', 'river', 936, 350),
 ('SoRu39389224', 'river', 936, 350),
 ('SoMa34494224', 'river', 936, 350),
 ('SoRu36805224', 'river', 936, 350),
 ('SoRu37362224', 'river', 936, 350),
 ('SoRu36403224', 'river', 934, 358),
 ('SoRu37286224', 'river', 934, 358),
 ('KiZu31008224', 'river', 934, 358),
 ('SoBa31806224', 'river', 934, 358),
 ('KiRu27555224', 'river', 934, 358),
 ('KiRu29801224', 'river', 934, 358),
 ('KiIs23486224', 'river', 934, 358),
 ('HaRu19170224', 'river', 934, 358),
 ('KiIs23965224', 'river', 932, 366),
 ('KiRu30162224', 'river', 932, 366),
 ('SoKo33077224', 'river', 932, 366),
 ('SoRu35148224', 'river', 932, 366),
 ('SoRu37421224', 'river', 932, 366),
 ('SoRu34742224', 'river', 932, 366),
 ('SoRu36384224', 'river', 932, 366),
 ('KiRu29036224', 'river', 932, 366),
 ('KiRu27525224', 'river', 932, 366),
 ('KiRu27566224', 'river', 932, 366),
 ('KiRu27225224', 'river', 932, 366),
 ('AmAs10202224', 'river', 932, 366),
 ('AmAs10741224', 'river', 932, 366),
 ('SoRu38603224', 'river', 932, 366),
 ('SoRu39133224', 'river', 932, 366),
 ('AkRu07891224', 'river', 932, 366),
 ('KiRu25683224', 'river', 930, 382),
 ('AkRu03096224', 'river', 930, 382),
 ('SoRu38206224', 'river', 930, 382),
 ('SoRu35548224', 'river', 930, 382),
 ('SoKo33262224', 'river', 930, 382),
 ('KiRu30654224', 'river', 930, 382),
 ('SoRu39106224', 'river', 930, 382),
 ('SoRu38802224', 'river', 930, 382),
 ('SoRu39535224', 'river', 930, 382),
 ('AmAm09438224', 'river', 930, 382),
 ('SoRu37358224', 'river', 928, 392),
 ('SoRu36836224', 'river', 928, 392),
 ('SoRu37056224', 'river', 928, 392),
 ('AkRu06100224', 'river', 928, 392),
 ('HaRu20314224', 'river', 928, 392),
 ('HaRu17912224', 'river', 928, 392),
 ('KiRu27288224', 'river', 928, 392),
 ('KiRu27971224', 'river', 928, 392),
 ('AkRu04085224', 'river', 928, 392),
 ('SoRu39407224', 'river', 928, 392),
 ('SoRu38678224', 'river', 928, 392),
 ('AmRu13793224', 'river', 928, 392),
 ('SoKo33475224', 'river', 928, 392),
 ('SoMa34378224', 'river', 928, 392),
 ('SoCh32201224', 'river', 926, 406),
 ('SoIl32431224', 'river', 926, 406),
 ('KiRu30154224', 'river', 926, 406),
 ('KiRu26560224', 'river', 926, 406),
 ('AmAs10308224', 'river', 926, 406),
 ('SoRu35637224', 'river', 926, 406),
 ('SoRu37884224', 'river', 926, 406),
 ('SoRu36166224', 'river', 926, 406),
 ('SoRu34918224', 'river', 926, 406),
 ('SoRu37687224', 'river', 926, 406),
 ('AkLu02460224', 'river', 926, 406),
 ('AkRu02865224', 'river', 924, 417),
 ('KiRu29918224', 'river', 924, 417),
 ('AkRu07200224', 'river', 924, 417),
 ('KiZu31012224', 'river', 924, 417),
 ('KiZu30955224', 'river', 924, 417),
 ('SoKo33314224', 'river', 924, 417),
 ('SoRu37903224', 'river', 924, 417),
 ('SoRu37549224', 'river', 924, 417),
 ('KiRu29599224', 'river', 922, 425),
 ('AkRu02987224', 'river', 922, 425),
 ('AkRu03500224', 'river', 922, 425),
 ('SoIl32806224', 'river', 922, 425),
 ('AmRu13633224', 'river', 922, 425),
 ('AmRu14055224', 'river', 922, 425),
 ('SoRu38377224', 'river', 922, 425),
 ('SoRu39637224', 'river', 920, 432),
 ('SoRu38789224', 'river', 920, 432),
 ('KiRu26860224', 'river', 920, 432),
 ('SoRu36223224', 'river', 920, 432),
 ('SoRu35326224', 'river', 920, 432),
 ('SoRu35602224', 'river', 920, 432),
 ('SoRu37932224', 'river', 920, 432),
 ('SoRu36465224', 'river', 920, 432),
 ('SoRu38159224', 'river', 920, 432),
 ('HaRu20556224', 'river', 920, 432),
 ('KiRu26174224', 'river', 920, 432),
 ('KiMr24827224', 'river', 920, 432),
 ('SoBa31825224', 'river', 920, 432),
 ('SoMa34258224', 'river', 918, 445),
 ('SoIl32554224', 'river', 918, 445),
 ('SoMa33930224', 'river', 918, 445),
 ('SoKo33116224', 'river', 918, 445),
 ('SoRu35748224', 'river', 918, 445),
 ('SoRu37075224', 'river', 918, 445),
 ('KiRu26217224', 'river', 918, 445),
 ('KiRu28563224', 'river', 918, 445),
 ('KiAm22618224', 'river', 918, 445),
 ('AkHa00232224', 'river', 918, 445),
 ('AkRu04147224', 'river', 918, 445),
 ('SoRu37149224', 'river', 916, 456),
 ('SoRu34766224', 'river', 916, 456),
 ('SoRu36273224', 'river', 916, 456),
 ('AmPw12326224', 'river', 916, 456),
 ('AkRu05389224', 'river', 916, 456),
 ('AkRu07339224', 'river', 916, 456),
 ('AkRu07041224', 'river', 916, 456),
 ('SoBa31897224', 'river', 916, 456),
 ('KiZu31274224', 'river', 916, 456),
 ('SoKo33315224', 'river', 914, 465),
 ('SoRu35623224', 'river', 914, 465),
 ('SoRu39194224', 'river', 914, 465),
 ('AkRu04233224', 'river', 914, 465),
 ('AmAs10630224', 'river', 914, 465),
 ('HaRu20360224', 'river', 914, 465),
 ('HaRu19185224', 'river', 914, 465),
 ('HaRu19566224', 'river', 912, 472),
 ('AmAm09523224', 'river', 912, 472),
 ('AmBe10951224', 'river', 912, 472),
 ('SoRu35825224', 'river', 912, 472),
 ('SoRu35180224', 'river', 912, 472),
 ('AkRu07680224', 'river', 912, 472),
 ('SoRu38340224', 'river', 912, 472),
 ('KiRu27712224', 'river', 912, 472),
 ('KiRu27728224', 'river', 912, 472),
 ('HaDe16315224', 'river', 912, 472),
 ('AmRu14167224', 'river', 910, 482),
 ('AkRu06673224', 'river', 910, 482),
 ('AkRu07333224', 'river', 910, 482),
 ('AkRu07221224', 'river', 910, 482),
 ('AmAm09603224', 'river', 910, 482),
 ('HaRu18599224', 'river', 910, 482),
 ('SoBa31570224', 'river', 910, 482),
 ('SoRu36445224', 'river', 910, 482),
 ('SoRu38079224', 'river', 910, 482),
 ('SoRu35306224', 'river', 910, 482),
 ('SoRu34962224', 'river', 910, 482),
 ('SoRu35487224', 'river', 910, 482),
 ('AkRu04283224', 'river', 910, 482),
 ('KiRu25964224', 'river', 910, 482),
 ('SoRu38301224', 'river', 910, 482),
 ('SoRu36056224', 'river', 908, 497),
 ('SoRu35764224', 'river', 908, 497),
 ('SoRu36115224', 'river', 908, 497),
 ('SoRu37543224', 'river', 908, 497),
 ('KiRu30424224', 'river', 908, 497),
 ('HaRu17692224', 'river', 908, 497),
 ('KiAm21974224', 'river', 908, 497),
 ('KiRu26712224', 'river', 908, 497),
 ('KiRu28787224', 'river', 908, 497),
 ('KiRu26546224', 'river', 908, 497),
 ('SoMa33799224', 'river', 906, 507),
 ('KiZu30865224', 'river', 906, 507),
 ('SoIl32464224', 'river', 906, 507),
 ('AmAm09393224', 'river', 906, 507),
 ('AmPw12370224', 'river', 906, 507),
 ('AmRu15264224', 'river', 906, 507),
 ('AkRu06501224', 'river', 906, 507),
 ('SoRu35755224', 'river', 906, 507),
 ('SoRu36561224', 'river', 906, 507),
 ('SoRu35471224', 'river', 906, 507),
 ('SoRu35419224', 'river', 906, 507),
 ('SoRu36365224', 'river', 906, 507),
 ('SoRu39040224', 'river', 906, 507),
 ('KiIs23620224', 'river', 906, 507),
 ('KiHa23281224', 'river', 906, 507),
 ('HaSe21113224', 'river', 906, 507),
 ('SoRu37507224', 'river', 904, 523),
 ('KiRu26417224', 'river', 904, 523),
 ('SoIl32883224', 'river', 904, 523),
 ('SoMa33931224', 'river', 904, 523),
 ('KiZu31227224', 'river', 904, 523),
 ('SoRu38356224', 'river', 904, 523),
 ('SoRu39211224', 'river', 904, 523),

In [8]:
%%sql
SELECT source_id, type_of_water_source,  number_of_people_served AS num_of_people_served, 
DENSE_RANK() OVER (PARTITION BY type_of_water_source 
         ORDER BY number_of_people_served ) AS Priority_of_ranking
FROM water_source
WHERE type_of_water_source != "tap_in_home"
LIMIT 1000;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
1000 rows affected.

[('SoRu38500224', 'river', 400, 1),
 ('SoRu39436224', 'river', 400, 1),
 ('SoRu38759224', 'river', 400, 1),
 ('SoRu38345224', 'river', 400, 1),
 ('SoRu37948224', 'river', 400, 1),
 ('SoRu37633224', 'river', 400, 1),
 ('SoRu34808224', 'river', 400, 1),
 ('KiRu27420224', 'river', 400, 1),
 ('AkKi01493224', 'river', 400, 1),
 ('SoMa33669224', 'river', 400, 1),
 ('SoMa33948224', 'river', 400, 1),
 ('SoKo33424224', 'river', 400, 1),
 ('KiMr24417224', 'river', 400, 1),
 ('KiHa23390224', 'river', 400, 1),
 ('AmRu14978224', 'river', 400, 1),
 ('HaDj16848224', 'river', 400, 1),
 ('HaAm15940224', 'river', 402, 2),
 ('SoRu34889224', 'river', 402, 2),
 ('SoRu37206224', 'river', 402, 2),
 ('SoRu35540224', 'river', 402, 2),
 ('SoRu34900224', 'river', 402, 2),
 ('SoRu35362224', 'river', 402, 2),
 ('KiRu29598224', 'river', 402, 2),
 ('KiRu27306224', 'river', 402, 2),
 ('KiMr24831224', 'river', 402, 2),
 ('KiIs23538224', 'river', 402, 2),
 ('KiIs23568224', 'river', 402, 2),
 ('KiIs24082224', 'river', 402, 2),
 ('AmAm09712224', 'river', 402, 2),
 ('SoIl32582224', 'river', 402, 2),
 ('SoIl32326224', 'river', 402, 2),
 ('KiRu30631224', 'river', 402, 2),
 ('KiRu30356224', 'river', 404, 3),
 ('SoBa31550224', 'river', 404, 3),
 ('KiRu30113224', 'river', 404, 3),
 ('SoRu34764224', 'river', 404, 3),
 ('SoMa34500224', 'river', 404, 3),
 ('SoRu37294224', 'river', 404, 3),
 ('SoRu34944224', 'river', 404, 3),
 ('AkRu05536224', 'river', 404, 3),
 ('SoRu38482224', 'river', 404, 3),
 ('KiRu27249224', 'river', 404, 3),
 ('KiRu29975224', 'river', 404, 3),
 ('KiRu28466224', 'river', 404, 3),
 ('KiRu26987224', 'river', 404, 3),
 ('AkRu06038224', 'river', 406, 4),
 ('SoRu37465224', 'river', 406, 4),
 ('SoRu36612224', 'river', 406, 4),
 ('SoRu38193224', 'river', 406, 4),
 ('SoRu37969224', 'river', 406, 4),
 ('SoRu36277224', 'river', 406, 4),
 ('AkHa00527224', 'river', 406, 4),
 ('KiZu30874224', 'river', 406, 4),
 ('SoMa33724224', 'river', 406, 4),
 ('SoBa31551224', 'river', 406, 4),
 ('KiZu30871224', 'river', 406, 4),
 ('SoRu38898224', 'river', 406, 4),
 ('AmDa11814224', 'river', 406, 4),
 ('KiHa22988224', 'river', 406, 4),
 ('KiHa23337224', 'river', 408, 5),
 ('SoRu35046224', 'river', 408, 5),
 ('KiRu26725224', 'river', 408, 5),
 ('SoMa33821224', 'river', 408, 5),
 ('KiZu30821224', 'river', 408, 5),
 ('KiRu30429224', 'river', 408, 5),
 ('KiZu30908224', 'river', 408, 5),
 ('SoRu37780224', 'river', 410, 6),
 ('SoRu37765224', 'river', 410, 6),
 ('SoRu35248224', 'river', 410, 6),
 ('SoMa34477224', 'river', 410, 6),
 ('SoRu35092224', 'river', 410, 6),
 ('SoRu35026224', 'river', 410, 6),
 ('KiMr24466224', 'river', 410, 6),
 ('AkRu07909224', 'river', 410, 6),
 ('AmAs10879224', 'river', 410, 6),
 ('AmAs10485224', 'river', 410, 6),
 ('SoRu38660224', 'river', 410, 6),
 ('KiHa23147224', 'river', 412, 7),
 ('SoRu35883224', 'river', 412, 7),
 ('SoRu34730224', 'river', 412, 7),
 ('SoRu35170224', 'river', 412, 7),
 ('SoRu36540224', 'river', 412, 7),
 ('SoBa31874224', 'river', 412, 7),
 ('SoBa31772224', 'river', 412, 7),
 ('SoIl32355224', 'river', 412, 7),
 ('SoMa33752224', 'river', 412, 7),
 ('KiRu29660224', 'river', 412, 7),
 ('AkRu07614224', 'river', 412, 7),
 ('AkRu05930224', 'river', 414, 8),
 ('SoRu37041224', 'river', 414, 8),
 ('SoRu36157224', 'river', 414, 8),
 ('KiRu25323224', 'river', 414, 8),
 ('KiRu25728224', 'river', 414, 8),
 ('SoRu39304224', 'river', 414, 8),
 ('SoRu38764224', 'river', 414, 8),
 ('SoRu39192224', 'river', 414, 8),
 ('HaRu17862224', 'river', 414, 8),
 ('KiRu27577224', 'river', 414, 8),
 ('KiRu29578224', 'river', 414, 8),
 ('KiRu27057224', 'river', 414, 8),
 ('KiRu26693224', 'river', 414, 8),
 ('SoBa31549224', 'river', 414, 8),
 ('SoBa31753224', 'river', 416, 9),
 ('SoRu38836224', 'river', 416, 9),
 ('SoRu37134224', 'river', 416, 9),
 ('SoRu37714224', 'river', 416, 9),
 ('SoRu37407224', 'river', 416, 9),
 ('KiHa23022224', 'river', 416, 9),
 ('KiRu28849224', 'river', 416, 9),
 ('KiRu27002224', 'river', 416, 9),
 ('AmAb09106224', 'river', 416, 9),
 ('AmRu13137224', 'river', 416, 9),
 ('HaRu18549224', 'river', 416, 9),
 ('HaRu19205224', 'river', 418, 10),
 ('SoRu37983224', 'river', 418, 10),
 ('SoRu36979224', 'river', 418, 10),
 ('SoMa34599224', 'river', 418, 10),
 ('SoRu38118224', 'river', 418, 10),
 ('SoRu35077224', 'river', 418, 10),
 ('SoMa34352224', 'river', 418, 10),
 ('KiZu31421224', 'river', 418, 10),
 ('SoIl32336224', 'river', 418, 10),
 ('AkRu03548224', 'river', 418, 10),
 ('SoRu39030224', 'river', 418, 10),
 ('HaAm15991224', 'river', 418, 10),
 ('KiRu25822224', 'river', 418, 10),
 ('SoRu39589224', 'river', 420, 11),
 ('SoRu35577224', 'river', 420, 11),
 ('SoRu34782224', 'river', 420, 11),
 ('AkRu02993224', 'river', 420, 11),
 ('KiZu31168224', 'river', 420, 11),
 ('SoKo33524224', 'river', 420, 11),
 ('AkRu08833224', 'river', 420, 11),
 ('AmAs10417224', 'river', 422, 12),
 ('AkRu04573224', 'river', 422, 12),
 ('AkRu05792224', 'river', 422, 12),
 ('SoRu35380224', 'river', 422, 12),
 ('SoRu37614224', 'river', 422, 12),
 ('SoRu36420224', 'river', 422, 12),
 ('SoRu39383224', 'river', 422, 12),
 ('SoRu39556224', 'river', 422, 12),
 ('SoKo33120224', 'river', 422, 12),
 ('SoRu36872224', 'river', 424, 13),
 ('KiHa22913224', 'river', 424, 13),
 ('AkRu05184224', 'river', 424, 13),
 ('AmPw12640224', 'river', 424, 13),
 ('SoRu38857224', 'river', 424, 13),
 ('SoRu38571224', 'river', 424, 13),
 ('SoRu38868224', 'river', 424, 13),
 ('SoRu38995224', 'river', 424, 13),
 ('SoIl32446224', 'river', 426, 14),
 ('SoRu37736224', 'river', 426, 14),
 ('SoRu37031224', 'river', 426, 14),
 ('AmAm09534224', 'river', 426, 14),
 ('AmRu15869224', 'river', 426, 14),
 ('KiRu27361224', 'river', 426, 14),
 ('KiRu28242224', 'river', 428, 15),
 ('KiRu26377224', 'river', 428, 15),
 ('KiRu28967224', 'river', 428, 15),
 ('KiRu29156224', 'river', 428, 15),
 ('SoBa31745224', 'river', 428, 15),
 ('HaRu19872224', 'river', 428, 15),
 ('AmRu14863224', 'river', 428, 15),
 ('SoRu37758224', 'river', 428, 15),
 ('SoRu35430224', 'river', 428, 15),
 ('SoRu34775224', 'river', 428, 15),
 ('SoRu34687224', 'river', 428, 15),
 ('AkRu08643224', 'river', 428, 15),
 ('KiRu28926224', 'river', 430, 16),
 ('AkRu06217224', 'river', 430, 16),
 ('AkRu06782224', 'river', 430, 16),
 ('AkRu06785224', 'river', 430, 16),
 ('AkRu04117224', 'river', 430, 16),
 ('AkRu03129224', 'river', 430, 16),
 ('SoRu39115224', 'river', 430, 16),
 ('SoRu37602224', 'river', 430, 16),
 ('SoRu37599224', 'river', 430, 16),
 ('AmRu15884224', 'river', 430, 16),
 ('AmRu13327224', 'river', 432, 17),
 ('KiZu30835224', 'river', 432, 17),
 ('SoCh32062224', 'river', 432, 17),
 ('SoIl32478224', 'river', 432, 17),
 ('SoMa34044224', 'river', 432, 17),
 ('AmDa11368224', 'river', 432, 17),
 ('KiMr24953224', 'river', 432, 17),
 ('KiHa23342224', 'river', 432, 17),
 ('SoMa34445224', 'river', 432, 17),
 ('SoRu35134224', 'river', 432, 17),
 ('SoRu35798224', 'river', 432, 17),
 ('HaRu19202224', 'river', 432, 17),
 ('SoRu38944224', 'river', 432, 17),
 ('AmAm09667224', 'river', 434, 18),
 ('AmRu13958224', 'river', 434, 18),
 ('KiRu28865224', 'river', 434, 18),
 ('KiRu29242224', 'river', 434, 18),
 ('AkRu03452224', 'river', 434, 18),
 ('KiZu31204224', 'river', 434, 18),
 ('KiZu31199224', 'river', 434, 18),
 ('HaRu17940224', 'river', 434, 18),
 ('KiIs23753224', 'river', 434, 18),
 ('KiRu25310224', 'river', 434, 18),
 ('SoRu37801224', 'river', 434, 18),
 ('SoRu37879224', 'river', 434, 18),
 ('SoRu37595224', 'river', 434, 18),
 ('SoRu36125224', 'river', 436, 19),
 ('SoRu36001224', 'river', 436, 19),
 ('SoRu37496224', 'river', 436, 19),
 ('SoRu36141224', 'river', 436, 19),
 ('SoRu38395224', 'river', 436, 19),
 ('SoRu39086224', 'river', 436, 19),
 ('SoRu39479224', 'river', 436, 19),
 ('SoRu39187224', 'river', 436, 19),
 ('AmAm09399224', 'river', 436, 19),
 ('AmRu13094224', 'river', 436, 19),
 ('KiRu26892224', 'river', 436, 19),
 ('AkRu07058224', 'river', 436, 19),
 ('AkRu07903224', 'river', 436, 19),
 ('KiMr24591224', 'river', 436, 19),
 ('KiZu30917224', 'river', 436, 19),
 ('SoBa31698224', 'river', 436, 19),
 ('SoMa33599224', 'river', 438, 20),
 ('SoCh32083224', 'river', 438, 20),
 ('SoKo33056224', 'river', 438, 20),
 ('KiRu29045224', 'river', 438, 20),
 ('SoRu36402224', 'river', 438, 20),
 ('SoRu35099224', 'river', 438, 20),
 ('SoRu37823224', 'river', 438, 20),
 ('SoRu37236224', 'river', 438, 20),
 ('SoMa34486224', 'river', 438, 20),
 ('AmRu15125224', 'river', 438, 20),
 ('AkLu02395224', 'river', 438, 20),
 ('AmAs10678224', 'river', 438, 20),
 ('AmDa11666224', 'river', 438, 20),
 ('AmBe11006224', 'river', 438, 20),
 ('SoRu39154224', 'river', 438, 20),
 ('SoRu39274224', 'river', 438, 20),
 ('AkRu06422224', 'river', 438, 20),
 ('AkRu05449224', 'river', 438, 20),
 ('AkRu05001224', 'river', 440, 21),
 ('SoRu37934224', 'river', 440, 21),
 ('SoRu35036224', 'river', 440, 21),
 ('SoRu35718224', 'river', 440, 21),
 ('SoRu35975224', 'river', 440, 21),
 ('SoRu35261224', 'river', 440, 21),
 ('SoKo33411224', 'river', 440, 21),
 ('KiRu27364224', 'river', 440, 21),
 ('KiRu27488224', 'river', 440, 21),
 ('HaAm16208224', 'river', 440, 21),
 ('SoRu39247224', 'river', 440, 21),
 ('SoRu38448224', 'river', 440, 21),
 ('SoRu39064224', 'river', 440, 21),
 ('SoRu39294224', 'river', 440, 21),
 ('KiMr25046224', 'river', 440, 21),
 ('KiHa23079224', 'river', 440, 21),
 ('KiIs24139224', 'river', 442, 22),
 ('KiRu29947224', 'river', 442, 22),
 ('KiRu27528224', 'river', 442, 22),
 ('SoRu35625224', 'river', 442, 22),
 ('SoRu37211224', 'river', 442, 22),
 ('SoCh31997224', 'river', 442, 22),
 ('KiZu31030224', 'river', 442, 22),
 ('SoMa33824224', 'river', 442, 22),
 ('AkRu03140224', 'river', 442, 22),
 ('AkHa00248224', 'river', 442, 22),
 ('SoCh32128224', 'river', 444, 23),
 ('AkRu08439224', 'river', 444, 23),
 ('AkRu05523224', 'river', 444, 23),
 ('SoRu38072224', 'river', 444, 23),
 ('SoRu35538224', 'river', 446, 24),
 ('SoRu36037224', 'river', 446, 24),
 ('AkRu05697224', 'river', 446, 24),
 ('KiRu26032224', 'river', 446, 24),
 ('SoIl32671224', 'river', 446, 24),
 ('SoKo33388224', 'river', 446, 24),
 ('KiRu27400224', 'river', 446, 24),
 ('SoRu38732224', 'river', 446, 24),
 ('SoRu37160224', 'river', 448, 25),
 ('SoRu35765224', 'river', 448, 25),
 ('SoRu36783224', 'river', 448, 25),
 ('SoRu37520224', 'river', 448, 25),
 ('AkRu08928224', 'river', 448, 25),
 ('KiHa22918224', 'river', 448, 25),
 ('AkRu06027224', 'river', 448, 25),
 ('AkRu06530224', 'river', 448, 25),
 ('AkRu07054224', 'river', 448, 25),
 ('KiRu27682224', 'river', 448, 25),
 ('HaSe20980224', 'river', 448, 25),
 ('HaRu18861224', 'river', 450, 26),
 ('HaRu18254224', 'river', 450, 26),
 ('KiHa23304224', 'river', 450, 26),
 ('KiMr24686224', 'river', 450, 26),
 ('KiHa23162224', 'river', 450, 26),
 ('SoRu39163224', 'river', 450, 26),
 ('SoRu38437224', 'river', 450, 26),
 ('SoBa31581224', 'river', 450, 26),
 ('AmAs10086224', 'river', 450, 26),
 ('SoRu35750224', 'river', 450, 26),
 ('SoRu35570224', 'river', 452, 27),
 ('SoRu35431224', 'river', 452, 27),
 ('AmAm09540224', 'river', 452, 27),
 ('AmRu13000224', 'river', 452, 27),
 ('KiMr25025224', 'river', 452, 27),
 ('KiAm22199224', 'river', 452, 27),
 ('SoMa33900224', 'river', 452, 27),
 ('SoCh32156224', 'river', 452, 27),
 ('SoBa31893224', 'river', 452, 27),
 ('SoRu38811224', 'river', 452, 27),
 ('SoRu38378224', 'river', 452, 27),
 ('SoRu38541224', 'river', 454, 28),
 ('SoKo33171224', 'river', 454, 28),
 ('SoIl33034224', 'river', 454, 28),
 ('SoMa34392224', 'river', 454, 28),
 ('KiZu30727224', 'river', 454, 28),
 ('SoRu36064224', 'river', 454, 28),
 ('SoRu37630224', 'river', 454, 28),
 ('SoRu35642224', 'river', 454, 28),
 ('HaRu19029224', 'river', 454, 28),
 ('AkRu05748224', 'river', 454, 28),
 ('AkRu07415224', 'river', 456, 29),
 ('SoRu34936224', 'river', 456, 29),
 ('SoRu36323224', 'river', 456, 29),
 ('SoRu37587224', 'river', 456, 29),
 ('SoRu35842224', 'river', 456, 29),
 ('KiRu30616224', 'river', 456, 29),
 ('SoRu38879224', 'river', 456, 29),
 ('SoRu39520224', 'river', 456, 29),
 ('AkRu03277224', 'river', 456, 29),
 ('KiIs23776224', 'river', 456, 29),
 ('HaRu18469224', 'river', 456, 29),
 ('HaDe16621224', 'river', 456, 29),
 ('SoKo33363224', 'river', 458, 30),
 ('SoRu34827224', 'river', 458, 30),
 ('SoRu35799224', 'river', 458, 30),
 ('SoRu37706224', 'river', 458, 30),
 ('SoRu37433224', 'river', 458, 30),
 ('SoRu36337224', 'river', 458, 30),
 ('SoRu35995224', 'river', 458, 30),
 ('SoRu39592224', 'river', 458, 30),
 ('SoRu39510224', 'river', 458, 30),
 ('HaRu18109224', 'river', 458, 30),
 ('KiRu29546224', 'river', 458, 30),
 ('KiRu27817224', 'river', 460, 31),
 ('KiRu29738224', 'river', 460, 31),
 ('SoRu34708224', 'river', 460, 31),
 ('SoRu36873224', 'river', 460, 31),
 ('SoRu36945224', 'river', 460, 31),
 ('SoRu38112224', 'river', 460, 31),
 ('SoRu36113224', 'river', 460, 31),
 ('SoRu35831224', 'river', 460, 31),
 ('AkRu07850224', 'river', 460, 31),
 ('KiZu31238224', 'river', 460, 31),
 ('SoMa34297224', 'river', 460, 31),
 ('HaRu18933224', 'river', 460, 31),
 ('HaSe21339224', 'river', 462, 32),
 ('KiRu29169224', 'river', 462, 32),
 ('KiRu27760224', 'river', 462, 32),
 ('SoRu36173224', 'river', 462, 32),
 ('AmPw12375224', 'river', 462, 32),
 ('SoIl32511224', 'river', 462, 32),
 ('KiRu30336224', 'river', 462, 32),
 ('SoBa31714224', 'river', 462, 32),
 ('KiRu25374224', 'river', 462, 32),
 ('KiMr24530224', 'river', 462, 32),
 ('KiMr24471224', 'river', 464, 33),
 ('SoRu35167224', 'river', 464, 33),
 ('SoRu35509224', 'river', 464, 33),
 ('SoRu38183224', 'river', 464, 33),
 ('AmRu15439224', 'river', 464, 33),
 ('KiRu28829224', 'river', 464, 33),
 ('SoIl32303224', 'river', 464, 33),
 ('AmAm09724224', 'river', 464, 33),
 ('SoRu39490224', 'river', 464, 33),
 ('SoRu35451224', 'river', 466, 34),
 ('SoRu34818224', 'river', 466, 34),
 ('SoRu34781224', 'river', 466, 34),
 ('HaRu17638224', 'river', 466, 34),
 ('AmDa11520224', 'river', 466, 34),
 ('AmAm09617224', 'river', 466, 34),
 ('SoMa33871224', 'river', 466, 34),
 ('SoMa34280224', 'river', 466, 34),
 ('SoMa33656224', 'river', 466, 34),
 ('SoIl32602224', 'river', 468, 35),
 ('SoBa31695224', 'river', 468, 35),
 ('SoMa33803224', 'river', 468, 35),
 ('SoMa33801224', 'river', 468, 35),
 ('KiZu31428224', 'river', 468, 35),
 ('SoRu36918224', 'river', 468, 35),
 ('SoRu36484224', 'river', 468, 35),
 ('SoRu35369224', 'river', 468, 35),
 ('SoRu37299224', 'river', 468, 35),
 ('KiRu25917224', 'river', 468, 35),
 ('SoRu39303224', 'river', 468, 35),
 ('AmBe11215224', 'river', 468, 35),
 ('KiRu27575224', 'river', 468, 35),
 ('KiRu26833224', 'river', 470, 36),
 ('KiRu25663224', 'river', 470, 36),
 ('KiRu30234224', 'river', 470, 36),
 ('AkRu08376224', 'river', 470, 36),
 ('SoRu35021224', 'river', 470, 36),
 ('AmRu15867224', 'river', 470, 36),
 ('HaDe16392224', 'river', 470, 36),
 ('AmAm09480224', 'river', 470, 36),
 ('SoRu39005224', 'river', 470, 36),
 ('HaRu18539224', 'river', 470, 36),
 ('SoRu37461224', 'river', 472, 37),
 ('SoRu37892224', 'river', 472, 37),
 ('SoRu37610224', 'river', 472, 37),
 ('KiRu25772224', 'river', 472, 37),
 ('KiRu26558224', 'river', 472, 37),
 ('SoKo33233224', 'river', 472, 37),
 ('KiRu30637224', 'river', 472, 37),
 ('SoIl32665224', 'river', 472, 37),
 ('SoMa33982224', 'river', 472, 37),
 ('KiZu31126224', 'river', 474, 38),
 ('KiRu29022224', 'river', 474, 38),
 ('SoRu36898224', 'river', 474, 38),
 ('HaRu18876224', 'river', 474, 38),
 ('KiIs23989224', 'river', 474, 38),
 ('AmAm09684224', 'river', 474, 38),
 ('AmAs10570224', 'river', 476, 39),
 ('KiRu27319224', 'river', 476, 39),
 ('KiRu29951224', 'river', 476, 39),
 ('SoBa31669224', 'river', 476, 39),
 ('KiZu31110224', 'river', 476, 39),
 ('SoMa34006224', 'river', 476, 39),
 ('SoRu36861224', 'river', 476, 39),
 ('SoRu36629224', 'river', 476, 39),
 ('SoRu36920224', 'river', 476, 39),
 ('AkRu07036224', 'river', 476, 39),
 ('KiAm22388224', 'river', 476, 39),
 ('AmRu15675224', 'river', 476, 39),
 ('SoRu39493224', 'river', 476, 39),
 ('SoRu35549224', 'river', 478, 40),
 ('SoMa34470224', 'river', 478, 40),
 ('SoRu36605224', 'river', 478, 40),
 ('SoRu35468224', 'river', 478, 40),
 ('AkRu08921224', 'river', 478, 40),
 ('AmBe11313224', 'river', 478, 40),
 ('HaRu20825224', 'river', 478, 40),
 ('KiZu30959224', 'river', 478, 40),
 ('AkRu07303224', 'river', 478, 40),
 ('AkRu06175224', 'river', 478, 40),
 ('KiRu25984224', 'river', 478, 40),
 ('KiIs23910224', 'river', 478, 40),
 ('KiHa23231224', 'river', 478, 40),
 ('KiRu25290224', 'river', 478, 40),
 ('KiRu26187224', 'river', 480, 41),
 ('KiRu25602224', 'river', 480, 41),
 ('KiMr25012224', 'river', 480, 41),
 ('KiMr24440224', 'river', 480, 41),
 ('SoRu37551224', 'river', 480, 41),
 ('SoRu36028224', 'river', 480, 41),
 ('SoRu35456224', 'river', 480, 41),
 ('SoRu35574224', 'river', 480, 41),
 ('SoRu37721224', 'river', 480, 41),
 ('SoRu39471224', 'river', 480, 41),
 ('SoRu39452224', 'river', 480, 41),
 ('SoRu39100224', 'river', 480, 41),
 ('SoRu39610224', 'river', 480, 41),
 ('KiRu27741224', 'river', 480, 41),
 ('KiRu28440224', 'river', 480, 41),
 ('SoMa34250224', 'river', 480, 41),
 ('KiRu30038224', 'river', 482, 42),
 ('SoMa33622224', 'river', 482, 42),
 ('SoKo33452224', 'river', 482, 42),
 ('SoKo33281224', 'river', 482, 42),
 ('SoMa34192224', 'river', 482, 42),
 ('SoRu38710224', 'river', 482, 42),
 ('KiMr24518224', 'river', 482, 42),
 ('AkRu04512224', 'river', 482, 42),
 ('SoRu35136224', 'river', 482, 42),
 ('SoRu36643224', 'river', 482, 42),
 ('SoRu36472224', 'river', 482, 42),
 ('KiRu27576224', 'river', 482, 42),
 ('KiRu28923224', 'river', 482, 42),
 ('AkRu05446224', 'river', 482, 42),
 ('AkRu07608224', 'river', 484, 43),
 ('AkRu06451224', 'river', 484, 43),
 ('AkRu03370224', 'river', 484, 43),
 ('SoRu38704224', 'river', 484, 43),
 ('HaRu17945224', 'river', 484, 43),
 ('SoMa34325224', 'river', 484, 43),
 ('KiMr24420224', 'river', 484, 43),
 ('AmBe11040224', 'river', 484, 43),
 ('KiRu26394224', 'river', 484, 43),
 ('SoRu36621224', 'river', 484, 43),
 ('SoRu38172224', 'river', 484, 43),
 ('SoRu35948224', 'river', 484, 43),
 ('SoRu37220224', 'river', 486, 44),
 ('SoRu36372224', 'river', 486, 44),
 ('SoRu36318224', 'river', 486, 44),
 ('KiHa22698224', 'river', 486, 44),
 ('KiRu25270224', 'river', 486, 44),
 ('SoIl32469224', 'river', 486, 44),
 ('SoIl32657224', 'river', 486, 44),
 ('SoKo33466224', 'river', 486, 44),
 ('KiZu31019224', 'river', 486, 44),
 ('SoMa34115224', 'river', 486, 44),
 ('SoKo33502224', 'river', 488, 45),
 ('SoRu39218224', 'river', 488, 45),
 ('SoRu37896224', 'river', 488, 45),
 ('SoMa34452224', 'river', 488, 45),
 ('AmRu15289224', 'river', 488, 45),
 ('KiIs23638224', 'river', 490, 46),
 ('KiIs23696224', 'river', 490, 46),
 ('AkRu02650224', 'river', 490, 46),
 ('KiZu30911224', 'river', 490, 46),
 ('SoIl32400224', 'river', 490, 46),
 ('KiZu30810224', 'river', 490, 46),
 ('HaRu18995224', 'river', 490, 46),
 ('HaRu19841224', 'river', 490, 46),
 ('SoRu34901224', 'river', 490, 46),
 ('SoRu34739224', 'river', 490, 46),
 ('AmBe11315224', 'river', 490, 46),
 ('AmAs10917224', 'river', 490, 46),
 ('KiZu31364224', 'river', 492, 47),
 ('SoMa34109224', 'river', 492, 47),
 ('AkRu05725224', 'river', 492, 47),
 ('AkRu05696224', 'river', 492, 47),
 ('AkRu05477224', 'river', 492, 47),
 ('SoRu38298224', 'river', 492, 47),
 ('AkRu04285224', 'river', 492, 47),
 ('KiRu26527224', 'river', 492, 47),
 ('HaSe21311224', 'river', 492, 47),
 ('HaRu19612224', 'river', 492, 47),
 ('SoBa31523224', 'river', 494, 48),
 ('SoIl32922224', 'river', 494, 48),
 ('AmAs10054224', 'river', 494, 48),
 ('KiRu27696224', 'river', 494, 48),
 ('SoRu36418224', 'river', 494, 48),
 ('SoRu36520224', 'river', 494, 48),
 ('SoRu38186224', 'river', 494, 48),
 ('SoRu35031224', 'river', 494, 48),
 ('SoRu35655224', 'river', 494, 48),
 ('SoRu37593224', 'river', 494, 48),
 ('SoRu36075224', 'river', 494, 48),
 ('SoRu37929224', 'river', 496, 49),
 ('SoRu35886224', 'river', 496, 49),
 ('SoRu34681224', 'river', 496, 49),
 ('SoBa31563224', 'river', 496, 49),
 ('SoRu38965224', 'river', 496, 49),
 ('SoRu38389224', 'river', 496, 49),
 ('KiRu27806224', 'river', 496, 49),

In [137]:
%%sql
SELECT DATEDIFF(MAX(time_of_record), MIN(time_of_record)) AS Date_diff
FROM visits;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
1 rows affected.

[(924,)]

In [138]:
%%sql
SELECT ROUND(AVG(NULLIF(time_in_queue, 0))) as Avg_queue_time
FROM visits
WHERE time_in_queue != 0;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
1 rows affected.

[(Decimal('123'),)]

In [139]:
%%sql
SELECT *
FROM visits
LIMIT 300;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
300 rows affected.

[(0, 'SoIl32582', 'SoIl32582224', datetime.datetime(2021, 1, 1, 9, 10), 1, 15, 12),
 (1, 'KiRu28935', 'KiRu28935224', datetime.datetime(2021, 1, 1, 9, 17), 1, 0, 46),
 (2, 'HaRu19752', 'HaRu19752224', datetime.datetime(2021, 1, 1, 9, 36), 1, 62, 40),
 (3, 'AkLu01628', 'AkLu01628224', datetime.datetime(2021, 1, 1, 9, 53), 1, 0, 1),
 (4, 'AkRu03357', 'AkRu03357224', datetime.datetime(2021, 1, 1, 10, 11), 1, 28, 14),
 (5, 'KiRu29315', 'KiRu29315224', datetime.datetime(2021, 1, 1, 10, 17), 1, 9, 40),
 (6, 'AkRu05234', 'AkRu05234224', datetime.datetime(2021, 1, 1, 10, 18), 1, 0, 30),
 (7, 'KiRu28520', 'KiRu28520224', datetime.datetime(2021, 1, 1, 10, 28), 1, 0, 34),
 (8, 'HaZa21742', 'HaZa21742224', datetime.datetime(2021, 1, 1, 10, 37), 1, 0, 6),
 (9, 'AmDa12214', 'AmDa12214224', datetime.datetime(2021, 1, 1, 10, 58), 1, 0, 36),
 (10, 'HaRu19725', 'HaRu19725224', datetime.datetime(2021, 1, 1, 11, 4), 1, 0, 16),
 (11, 'KiRu26704', 'KiRu26704224', datetime.datetime(2021, 1, 1, 11, 4), 1, 17, 26),
 (12, 'SoRu35008', 'SoRu35008224', datetime.datetime(2021, 1, 1, 11, 4), 1, 240, 1),
 (13, 'AkKi00851', 'AkKi00851224', datetime.datetime(2021, 1, 1, 11, 14), 1, 0, 32),
 (14, 'AmDa11956', 'AmDa11956224', datetime.datetime(2021, 1, 1, 11, 16), 1, 0, 6),
 (15, 'SoRu35703', 'SoRu35703224', datetime.datetime(2021, 1, 1, 11, 29), 1, 0, 32),
 (16, 'HaRu17502', 'HaRu17502224', datetime.datetime(2021, 1, 1, 11, 33), 1, 0, 48),
 (17, 'AkHa00070', 'AkHa00070224', datetime.datetime(2021, 1, 1, 11, 42), 1, 0, 40),
 (18, 'HaSe21263', 'HaSe21263224', datetime.datetime(2021, 1, 1, 11, 51), 1, 0, 12),
 (19, 'HaSe21346', 'HaSe21346224', datetime.datetime(2021, 1, 1, 11, 52), 1, 0, 30),
 (20, 'KiHa23304', 'KiHa23304224', datetime.datetime(2021, 1, 1, 12, 0), 1, 20, 30),
 (21, 'KiRu26190', 'KiRu26190224', datetime.datetime(2021, 1, 1, 12, 0), 1, 171, 46),
 (22, 'HaYa21468', 'HaYa21468224', datetime.datetime(2021, 1, 1, 12, 3), 1, 0, 8),
 (23, 'HaSe21154', 'HaSe21154224', datetime.datetime(2021, 1, 1, 12, 12), 1, 0, 7),
 (24, 'AmRu14009', 'AmRu14009224', datetime.datetime(2021, 1, 1, 12, 16), 1, 0, 3),
 (25, 'SoRu36278', 'SoRu36278224', datetime.datetime(2021, 1, 1, 12, 24), 1, 0, 48),
 (26, 'AkLu02155', 'AkLu02155224', datetime.datetime(2021, 1, 1, 12, 29), 1, 0, 16),
 (27, 'KiHa23159', 'KiHa23159224', datetime.datetime(2021, 1, 1, 12, 34), 1, 0, 5),
 (28, 'AkLu02259', 'AkLu02259224', datetime.datetime(2021, 1, 1, 12, 42), 1, 0, 12),
 (29, 'AkRu06938', 'AkRu06938224', datetime.datetime(2021, 1, 1, 12, 56), 1, 0, 30),
 (30, 'AkKi01222', 'AkKi01222224', datetime.datetime(2021, 1, 1, 13, 4), 1, 0, 48),
 (31, 'AkRu05825', 'AkRu05825224', datetime.datetime(2021, 1, 1, 13, 7), 1, 0, 36),
 (32, 'HaRu17116', 'HaRu17116224', datetime.datetime(2021, 1, 1, 13, 38), 1, 28, 40),
 (33, 'AmAb08963', 'AmAb08963224', datetime.datetime(2021, 1, 1, 13, 40), 1, 0, 18),
 (34, 'AkRu05973', 'AkRu05973224', datetime.datetime(2021, 1, 1, 13, 44), 1, 0, 30),
 (35, 'SoRu36313', 'SoRu36313224', datetime.datetime(2021, 1, 1, 13, 46), 1, 0, 18),
 (36, 'KiMr24968', 'KiMr24968224', datetime.datetime(2021, 1, 1, 13, 52), 1, 0, 30),
 (37, 'HaRu18204', 'HaRu18204224', datetime.datetime(2021, 1, 1, 13, 53), 1, 16, 8),
 (38, 'KiRu30598', 'KiRu30598224', datetime.datetime(2021, 1, 1, 13, 54), 1, 56, 30),
 (39, 'KiMr25096', 'KiMr25096224', datetime.datetime(2021, 1, 1, 14, 0), 1, 11, 32),
 (40, 'SoRu35294', 'SoRu35294224', datetime.datetime(2021, 1, 1, 14, 7), 1, 24, 5),
 (41, 'AmDa12232', 'AmDa12232224', datetime.datetime(2021, 1, 1, 14, 10), 1, 0, 4),
 (42, 'SoRu36138', 'SoRu36138224', datetime.datetime(2021, 1, 1, 14, 14), 1, 0, 5),
 (43, 'KiRu27916', 'KiRu27916224', datetime.datetime(2021, 1, 1, 14, 19), 1, 0, 48),
 (44, 'KiMr24569', 'KiMr24569224', datetime.datetime(2021, 1, 1, 14, 30), 1, 0, 30),
 (45, 'SoRu35508', 'SoRu35508224', datetime.datetime(2021, 1, 1, 14, 49), 1, 0, 1),
 (46, 'SoCh32153', 'SoCh32153224', datetime.datetime(2021, 1, 1, 14, 56), 1, 0, 1),
 (47, 'KiRu27248', 'KiRu27248224', datetime.datetime(2021, 1, 1, 15, 11), 1, 211, 26),
 (48, 'AmDa11460', 'AmDa11460224', datetime.datetime(2021, 1, 1, 15, 17), 1, 0, 6),
 (49, 'KiIs23592', 'KiIs23592224', datetime.datetime(2021, 1, 1, 15, 41), 1, 0, 10),
 (50, 'AmDa11976', 'AmDa11976224', datetime.datetime(2021, 1, 1, 16, 0), 1, 0, 28),
 (51, 'AkHa00706', 'AkHa00706224', datetime.datetime(2021, 1, 1, 16, 10), 1, 0, 8),
 (52, 'AkRu03463', 'AkRu03463224', datetime.datetime(2021, 1, 1, 16, 10), 1, 16, 48),
 (53, 'AkHa00465', 'AkHa00465224', datetime.datetime(2021, 1, 1, 16, 28), 1, 0, 3),
 (54, 'HaRu17302', 'HaRu17302224', datetime.datetime(2021, 1, 1, 16, 32), 1, 0, 28),
 (55, 'AmRu14425', 'AmRu14425224', datetime.datetime(2021, 1, 1, 16, 32), 1, 0, 36),
 (56, 'HaSe21309', 'HaSe21309224', datetime.datetime(2021, 1, 1, 16, 36), 1, 0, 10),
 (57, 'SoRu39241', 'SoRu39241224', datetime.datetime(2021, 1, 1, 16, 40), 1, 0, 7),
 (58, 'KiRu30598', 'KiRu30598224', datetime.datetime(2021, 1, 2, 7, 7), 2, 107, 30),
 (59, 'SoRu35008', 'SoRu35008224', datetime.datetime(2021, 1, 2, 7, 27), 2, 248, 1),
 (60, 'HaRu19752', 'HaRu19752224', datetime.datetime(2021, 1, 2, 9, 4), 2, 73, 40),
 (61, 'KiRu27248', 'KiRu27248224', datetime.datetime(2021, 1, 2, 11, 2), 2, 167, 26),
 (62, 'KiRu26190', 'KiRu26190224', datetime.datetime(2021, 1, 2, 13, 56), 2, 200, 46),
 (63, 'KiRu27248', 'KiRu27248224', datetime.datetime(2021, 1, 3, 9, 41), 3, 103, 26),
 (64, 'HaRu19752', 'HaRu19752224', datetime.datetime(2021, 1, 3, 11, 38), 3, 39, 40),
 (65, 'KiRu26190', 'KiRu26190224', datetime.datetime(2021, 1, 3, 12, 0), 3, 112, 46),
 (66, 'KiRu30598', 'KiRu30598224', datetime.datetime(2021, 1, 3, 14, 8), 3, 30, 30),
 (67, 'SoRu35008', 'SoRu35008224', datetime.datetime(2021, 1, 3, 14, 31), 3, 104, 1),
 (68, 'KiRu30598', 'KiRu30598224', datetime.datetime(2021, 1, 4, 7, 46), 4, 89, 30),
 (69, 'HaRu20773', 'HaRu20773224', datetime.datetime(2021, 1, 4, 9, 8), 1, 0, 42),
 (70, 'HaRu19752', 'HaRu19752224', datetime.datetime(2021, 1, 4, 9, 24), 4, 75, 40),
 (71, 'AmRu13250', 'AmRu13250224', datetime.datetime(2021, 1, 4, 9, 34), 1, 0, 16),
 (72, 'AmRu15135', 'AmRu15135224', datetime.datetime(2021, 1, 4, 9, 38), 1, 0, 26),
 (73, 'AkLu01584', 'AkLu01584224', datetime.datetime(2021, 1, 4, 9, 46), 1, 0, 18),
 (74, 'SoRu39205', 'SoRu39205224', datetime.datetime(2021, 1, 4, 9, 59), 1, 0, 36),
 (75, 'HaDj16683', 'HaDj16683224', datetime.datetime(2021, 1, 4, 10, 16), 1, 0, 6),
 (76, 'AmRu14759', 'AmRu14759224', datetime.datetime(2021, 1, 4, 10, 30), 1, 0, 16),
 (77, 'AmRu14584', 'AmRu14584224', datetime.datetime(2021, 1, 4, 10, 39), 1, 0, 30),
 (78, 'KiZu31052', 'KiZu31052224', datetime.datetime(2021, 1, 4, 11, 5), 1, 0, 24),
 (79, 'AmPw12286', 'AmPw12286224', datetime.datetime(2021, 1, 4, 11, 16), 1, 24, 30),
 (80, 'HaRu18434', 'HaRu18434224', datetime.datetime(2021, 1, 4, 11, 16), 1, 0, 48),
 (81, 'HaDe16379', 'HaDe16379224', datetime.datetime(2021, 1, 4, 11, 21), 1, 0, 5),
 (82, 'HaRu18256', 'HaRu18256224', datetime.datetime(2021, 1, 4, 11, 26), 1, 29, 1),
 (83, 'AkRu04914', 'AkRu04914224', datetime.datetime(2021, 1, 4, 11, 35), 1, 0, 40),
 (84, 'HaSe20931', 'HaSe20931224', datetime.datetime(2021, 1, 4, 11, 46), 1, 0, 1),
 (85, 'SoRu35008', 'SoRu35008224', datetime.datetime(2021, 1, 4, 12, 12), 4, 165, 1),
 (86, 'AkRu04543', 'AkRu04543224', datetime.datetime(2021, 1, 4, 12, 20), 1, 0, 4),
 (87, 'KiAm22119', 'KiAm22119224', datetime.datetime(2021, 1, 4, 12, 34), 1, 0, 36),
 (88, 'AkLu02619', 'AkLu02619224', datetime.datetime(2021, 1, 4, 12, 46), 1, 0, 5),
 (89, 'AmRu15066', 'AmRu15066224', datetime.datetime(2021, 1, 4, 12, 47), 1, 0, 28),
 (90, 'SoRu37843', 'SoRu37843224', datetime.datetime(2021, 1, 4, 12, 49), 1, 59, 10),
 (91, 'AkLu02211', 'AkLu02211224', datetime.datetime(2021, 1, 4, 12, 49), 1, 0, 30),
 (92, 'AmRu15398', 'AmRu15398224', datetime.datetime(2021, 1, 4, 12, 53), 1, 0, 8),
 (93, 'HaDe16499', 'HaDe16499224', datetime.datetime(2021, 1, 4, 12, 53), 1, 0, 8),
 (94, 'SoRu39347', 'SoRu39347224', datetime.datetime(2021, 1, 4, 12, 54), 1, 0, 8),
 (95, 'AmAm09579', 'AmAm09579224', datetime.datetime(2021, 1, 4, 13, 2), 1, 0, 3),
 (96, 'HaRu17247', 'HaRu17247224', datetime.datetime(2021, 1, 4, 13, 18), 1, 0, 1),
 (97, 'AkRu04602', 'AkRu04602224', datetime.datetime(2021, 1, 4, 14, 2), 1, 0, 36),
 (98, 'KiMr25211', 'KiMr25211224', datetime.datetime(2021, 1, 4, 14, 16), 1, 123, 3),
 (99, 'AkRu07283', 'AkRu07283224', datetime.datetime(2021, 1, 4, 14, 19), 1, 0, 30),
 (100, 'SoCh32247', 'SoCh32247224', datetime.datetime(2021, 1, 4, 14, 23), 1, 0, 38),
 (101, 'SoIl32868', 'SoIl32868224', datetime.datetime(2021, 1, 4, 14, 29), 1, 0, 8),
 (102, 'SoKo33558', 'SoKo33558224', datetime.datetime(2021, 1, 4, 14, 46), 1, 14, 10),
 (103, 'HaRu20738', 'HaRu20738224', datetime.datetime(2021, 1, 4, 14, 57), 1, 0, 0),
 (104, 'AmAs10416', 'AmAs10416224', datetime.datetime(2021, 1, 4, 14, 58), 1, 0, 10),
 (105, 'AkLu02115', 'AkLu02115224', datetime.datetime(2021, 1, 4, 15, 3), 1, 0, 5),
 (106, 'KiRu27248', 'KiRu27248224', datetime.datetime(2021, 1, 4, 15, 4), 4, 218, 26),
 (107, 'HaAm16229', 'HaAm16229224', datetime.datetime(2021, 1, 4, 15, 10), 1, 0, 18),
 (108, 'HaRu20104', 'HaRu20104224', datetime.datetime(2021, 1, 4, 15, 17), 1, 0, 32),
 (109, 'KiHa23405', 'KiHa23405224', datetime.datetime(2021, 1, 4, 15, 29), 1, 0, 38),
 (110, 'SoRu37081', 'SoRu37081224', datetime.datetime(2021, 1, 4, 15, 33), 1, 9, 5),
 (111, 'KiRu27870', 'KiRu27870224', datetime.datetime(2021, 1, 4, 15, 46), 1, 0, 10),
 (112, 'HaYa21510', 'HaYa21510224', datetime.datetime(2021, 1, 4, 15, 46), 1, 0, 42),
 (113, 'SoBa31534', 'SoBa31534224', datetime.datetime(2021, 1, 4, 15, 50), 1, 0, 48),
 (114, 'AmDa11574', 'AmDa11574224', datetime.datetime(2021, 1, 4, 15, 51), 1, 0, 28),
 (115, 'AkRu03074', 'AkRu03074224', datetime.datetime(2021, 1, 4, 15, 51), 1, 0, 42),
 (116, 'SoRu37178', 'SoRu37178224', datetime.datetime(2021, 1, 4, 15, 53), 1, 0, 1),
 (117, 'SoRu38743', 'SoRu38743224', datetime.datetime(2021, 1, 4, 15, 56), 1, 0, 12),
 (118, 'AkRu04162', 'AkRu04162224', datetime.datetime(2021, 1, 4, 16, 21), 1, 10, 32),
 (119, 'KiRu26395', 'KiRu26395224', datetime.datetime(2021, 1, 4, 16, 21), 1, 0, 48),
 (120, 'HaDj16798', 'HaDj16798224', datetime.datetime(2021, 1, 4, 16, 30), 1, 0, 42),
 (121, 'HaSe21113', 'HaSe21113224', datetime.datetime(2021, 1, 4, 16, 31), 1, 14, 46),
 (122, 'AmAm09513', 'AmAm09513224', datetime.datetime(2021, 1, 4, 16, 34), 1, 0, 0),
 (123, 'AmPw12464', 'AmPw12464224', datetime.datetime(2021, 1, 4, 16, 34), 1, 0, 5),
 (124, 'AmRu15067', 'AmRu15067224', datetime.datetime(2021, 1, 4, 16, 42), 1, 0, 34),
 (125, 'KiRu26713', 'KiRu26713224', datetime.datetime(2021, 1, 4, 16, 52), 1, 0, 34),
 (126, 'KiRu26190', 'KiRu26190224', datetime.datetime(2021, 1, 4, 18, 2), 4, 176, 46),
 (127, 'KiRu30598', 'KiRu30598224', datetime.datetime(2021, 1, 5, 7, 58), 5, 29, 30),
 (128, 'SoRu35008', 'SoRu35008224', datetime.datetime(2021, 1, 5, 8, 13), 5, 213, 1),
 (129, 'HaRu20701', 'HaRu20701224', datetime.datetime(2021, 1, 5, 9, 1), 1, 0, 46),
 (130, 'AmRu13095', 'AmRu13095224', datetime.datetime(2021, 1, 5, 9, 7), 1, 0, 42),
 (131, 'SoMa34243', 'SoMa34243224', datetime.datetime(2021, 1, 5, 9, 17), 1, 0, 48),
 (132, 'AkRu08936', 'AkRu08936224', datetime.datetime(2021, 1, 5, 9, 22), 1, 0, 24),
 (133, 'KiAm22120', 'KiAm22120224', datetime.datetime(2021, 1, 5, 9, 23), 1, 0, 3),
 (134, 'AkRu03143', 'AkRu03143224', datetime.datetime(2021, 1, 5, 9, 24), 1, 0, 10),
 (135, 'AkRu05323', 'AkRu05323224', datetime.datetime(2021, 1, 5, 9, 25), 1, 21, 5),
 (136, 'SoRu34762', 'SoRu34762224', datetime.datetime(2021, 1, 5, 9, 39), 1, 0, 24),
 (137, 'KiMr25211', 'KiMr25211224', datetime.datetime(2021, 1, 5, 9, 47), 2, 64, 3),
 (138, 'AkRu06435', 'AkRu06435224', datetime.datetime(2021, 1, 5, 9, 56), 1, 0, 24),
 (139, 'AkRu03586', 'AkRu03586224', datetime.datetime(2021, 1, 5, 10, 12), 1, 0, 10),
 (140, 'KiHa22659', 'KiHa22659224', datetime.datetime(2021, 1, 5, 10, 16), 1, 0, 14),
 (141, 'AmRu13188', 'AmRu13188224', datetime.datetime(2021, 1, 5, 10, 22), 1, 0, 5),
 (142, 'AmBe11186', 'AmBe11186224', datetime.datetime(2021, 1, 5, 10, 24), 1, 0, 10),
 (143, 'HaRu19986', 'HaRu19986224', datetime.datetime(2021, 1, 5, 10, 25), 1, 22, 34),
 (144, 'HaRu19752', 'HaRu19752224', datetime.datetime(2021, 1, 5, 10, 35), 5, 28, 40),
 (145, 'AmBe11166', 'AmBe11166224', datetime.datetime(2021, 1, 5, 10, 46), 1, 19, 40),
 (146, 'SoRu38450', 'SoRu38450224', datetime.datetime(2021, 1, 5, 10, 48), 1, 0, 32),
 (147, 'AkRu07166', 'AkRu07166224', datetime.datetime(2021, 1, 5, 10, 59), 1, 0, 10),
 (148, 'SoRu35195', 'SoRu35195224', datetime.datetime(2021, 1, 5, 10, 59), 1, 14, 28),
 (149, 'AmAm09743', 'AmAm09743224', datetime.datetime(2021, 1, 5, 11, 6), 1, 0, 38),
 (150, 'KiZu30889', 'KiZu30889224', datetime.datetime(2021, 1, 5, 11, 12), 1, 240, 5),
 (151, 'KiZu31287', 'KiZu31287224', datetime.datetime(2021, 1, 5, 11, 17), 1, 0, 48),
 (152, 'KiRu30163', 'KiRu30163224', datetime.datetime(2021, 1, 5, 11, 22), 1, 0, 10),
 (153, 'AmRu13238', 'AmRu13238224', datetime.datetime(2021, 1, 5, 11, 26), 1, 0, 10),
 (154, 'KiRu26783', 'KiRu26783224', datetime.datetime(2021, 1, 5, 11, 52), 1, 0, 1),
 (155, 'AkHa00209', 'AkHa00209224', datetime.datetime(2021, 1, 5, 11, 52), 1, 0, 30),
 (156, 'KiIs23671', 'KiIs23671224', datetime.datetime(2021, 1, 5, 12, 6), 1, 0, 32),
 (157, 'HaAm15937', 'HaAm15937224', datetime.datetime(2021, 1, 5, 12, 9), 1, 42, 36),
 (158, 'AkHa00342', 'AkHa00342224', datetime.datetime(2021, 1, 5, 12, 24), 1, 0, 10),
 (159, 'HaSe20900', 'HaSe20900224', datetime.datetime(2021, 1, 5, 12, 40), 1, 0, 0),
 (160, 'KiIs23877', 'KiIs23877224', datetime.datetime(2021, 1, 5, 12, 41), 1, 0, 18),
 (161, 'AmRu14190', 'AmRu14190224', datetime.datetime(2021, 1, 5, 12, 49), 1, 0, 1),
 (162, 'SoBa31893', 'SoBa31893224', datetime.datetime(2021, 1, 5, 13, 2), 1, 10, 12),
 (163, 'KiRu26584', 'KiRu26584224', datetime.datetime(2021, 1, 5, 13, 10), 1, 0, 48),
 (164, 'AkRu08557', 'AkRu08557224', datetime.datetime(2021, 1, 5, 13, 14), 1, 127, 1),
 (165, 'AmAs10613', 'AmAs10613224', datetime.datetime(2021, 1, 5, 13, 24), 1, 24, 48),
 (166, 'AkLu02295', 'AkLu02295224', datetime.datetime(2021, 1, 5, 13, 31), 1, 0, 0),
 (167, 'AkRu07845', 'AkRu07845224', datetime.datetime(2021, 1, 5, 13, 52), 1, 0, 24),
 (168, 'AmAm09460', 'AmAm09460224', datetime.datetime(2021, 1, 5, 13, 58), 1, 0, 1),
 (169, 'SoRu38103', 'SoRu38103224', datetime.datetime(2021, 1, 5, 14, 0), 1, 0, 36),
 (170, 'KiMr25146', 'KiMr25146224', datetime.datetime(2021, 1, 5, 14, 2), 1, 0, 38),
 (171, 'AkRu05911', 'AkRu05911224', datetime.datetime(2021, 1, 5, 14, 4), 1, 145, 38),
 (172, 'HaRu20767', 'HaRu20767224', datetime.datetime(2021, 1, 5, 14, 8), 1, 0, 32),
 (173, 'KiRu26837', 'KiRu26837224', datetime.datetime(2021, 1, 5, 14, 9), 1, 0, 30),
 (174, 'KiRu25496', 'KiRu25496224', datetime.datetime(2021, 1, 5, 14, 13), 1, 0, 42),
 (175, 'AmRu13229', 'AmRu13229224', datetime.datetime(2021, 1, 5, 14, 17), 1, 0, 24),
 (176, 'KiRu25404', 'KiRu25404224', datetime.datetime(2021, 1, 5, 14, 39), 1, 0, 2),
 (177, 'AmDa11668', 'AmDa11668224', datetime.datetime(2021, 1, 5, 14, 41), 1, 0, 1),
 (178, 'SoRu35937', 'SoRu35937224', datetime.datetime(2021, 1, 5, 14, 45), 1, 0, 8),
 (179, 'SoRu37843', 'SoRu37843224', datetime.datetime(2021, 1, 5, 14, 59), 2, 56, 10),
 (180, 'AkKi01378', 'AkKi01378224', datetime.datetime(2021, 1, 5, 15, 9), 1, 0, 48),
 (181, 'AkRu04918', 'AkRu04918224', datetime.datetime(2021, 1, 5, 15, 10), 1, 0, 3),
 (182, 'KiRu25866', 'KiRu25866224', datetime.datetime(2021, 1, 5, 15, 31), 1, 0, 30),
 (183, 'SoRu36745', 'SoRu36745224', datetime.datetime(2021, 1, 5, 15, 34), 1, 25, 48),
 (184, 'KiRu28471', 'KiRu28471224', datetime.datetime(2021, 1, 5, 15, 54), 1, 0, 8),
 (185, 'AkRu03880', 'AkRu03880224', datetime.datetime(2021, 1, 5, 16, 8), 1, 0, 1),
 (186, 'HaRu19887', 'HaRu19887224', datetime.datetime(2021, 1, 5, 16, 21), 1, 0, 6),
 (187, 'AmAb09243', 'AmAb09243224', datetime.datetime(2021, 1, 5, 16, 22), 1, 0, 8),
 (188, 'KiHa23283', 'KiHa23283224', datetime.datetime(2021, 1, 5, 16, 25), 1, 0, 1),
 (189, 'AkRu07713', 'AkRu07713224', datetime.datetime(2021, 1, 5, 16, 27), 1, 0, 28),
 (190, 'AmAs10139', 'AmAs10139224', datetime.datetime(2021, 1, 5, 16, 32), 1, 20, 10),
 (191, 'AmAm09813', 'AmAm09813224', datetime.datetime(2021, 1, 5, 16, 40), 1, 27, 0),
 (192, 'HaRu19111', 'HaRu19111224', datetime.datetime(2021, 1, 5, 16, 43), 1, 30, 36),
 (193, 'KiRu26190', 'KiRu26190224', datetime.datetime(2021, 1, 5, 16, 46), 5, 175, 46),
 (194, 'AmAm09421', 'AmAm09421224', datetime.datetime(2021, 1, 5, 16, 54), 1, 0, 40),
 (195, 'KiRu27248', 'KiRu27248224', datetime.datetime(2021, 1, 5, 17, 36), 5, 226, 26),
 (196, 'KiRu30598', 'KiRu30598224', datetime.datetime(2021, 1, 6, 6, 21), 6, 36, 30),
 (197, 'KiRu26190', 'KiRu26190224', datetime.datetime(2021, 1, 6, 7, 6), 6, 80, 46),
 (198, 'AkRu04611', 'AkRu04611224', datetime.datetime(2021, 1, 6, 9, 6), 1, 179, 28),
 (199, 'KiRu28064', 'KiRu28064224', datetime.datetime(2021, 1, 6, 9, 10), 1, 5, 42),
 (200, 'HaRu18826', 'HaRu18826224', datetime.datetime(2021, 1, 6, 9, 20), 1, 0, 1),
 (201, 'SoRu37761', 'SoRu37761224', datetime.datetime(2021, 1, 6, 9, 28), 1, 10, 46),
 (202, 'AmBe11025', 'AmBe11025224', datetime.datetime(2021, 1, 6, 9, 32), 1, 0, 46),
 (203, 'SoRu35485', 'SoRu35485224', datetime.datetime(2021, 1, 6, 9, 43), 1, 30, 38),
 (204, 'AmRu14641', 'AmRu14641224', datetime.datetime(2021, 1, 6, 9, 49), 1, 0, 2),
 (205, 'AmRu13013', 'AmRu13013224', datetime.datetime(2021, 1, 6, 10, 6), 1, 0, 5),
 (206, 'KiRu27892', 'KiRu27892224', datetime.datetime(2021, 1, 6, 10, 11), 1, 0, 12),
 (207, 'KiRu25465', 'KiRu25465224', datetime.datetime(2021, 1, 6, 10, 15), 1, 0, 5),
 (208, 'AkRu07262', 'AkRu07262224', datetime.datetime(2021, 1, 6, 10, 18), 1, 0, 1),
 (209, 'AmRu13090', 'AmRu13090224', datetime.datetime(2021, 1, 6, 10, 19), 1, 0, 46),
 (210, 'AmRu15831', 'AmRu15831224', datetime.datetime(2021, 1, 6, 10, 21), 1, 0, 48),
 (211, 'HaRu17749', 'HaRu17749224', datetime.datetime(2021, 1, 6, 10, 38), 1, 0, 30),
 (212, 'SoKo33407', 'SoKo33407224', datetime.datetime(2021, 1, 6, 10, 40), 1, 27, 40),
 (213, 'HaSe21277', 'HaSe21277224', datetime.datetime(2021, 1, 6, 10, 46), 1, 0, 30),
 (214, 'HaRu17367', 'HaRu17367224', datetime.datetime(2021, 1, 6, 10, 48), 1, 18, 4),
 (215, 'SoRu36167', 'SoRu36167224', datetime.datetime(2021, 1, 6, 10, 52), 1, 0, 16),
 (216, 'AkRu07933', 'AkRu07933224', datetime.datetime(2021, 1, 6, 10, 52), 1, 0, 38),
 (217, 'KiZu30889', 'KiZu30889224', datetime.datetime(2021, 1, 6, 10, 54), 2, 242, 5),
 (218, 'HaDe16434', 'HaDe16434224', datetime.datetime(2021, 1, 6, 10, 57), 1, 0, 24),
 (219, 'AkRu03750', 'AkRu03750224', datetime.datetime(2021, 1, 6, 10, 57), 1, 23, 34),
 (220, 'AkHa00744', 'AkHa00744224', datetime.datetime(2021, 1, 6, 11, 14), 1, 0, 40),
 (221, 'AmRu14536', 'AmRu14536224', datetime.datetime(2021, 1, 6, 11, 17), 1, 167, 34),
 (222, 'AkHa00657', 'AkHa00657224', datetime.datetime(2021, 1, 6, 11, 22), 1, 0, 34),
 (223, 'HaRu19752', 'HaRu19752224', datetime.datetime(2021, 1, 6, 11, 25), 6, 39, 40),
 (224, 'AmRu13929', 'AmRu13929224', datetime.datetime(2021, 1, 6, 11, 31), 1, 0, 40),
 (225, 'AkKi01036', 'AkKi01036224', datetime.datetime(2021, 1, 6, 11, 40), 1, 0, 3),
 (226, 'AkRu08868', 'AkRu08868224', datetime.datetime(2021, 1, 6, 11, 51), 1, 0, 40),
 (227, 'AmDa12147', 'AmDa12147224', datetime.datetime(2021, 1, 6, 12, 2), 1, 18, 7),
 (228, 'AkHa00545', 'AkHa00545224', datetime.datetime(2021, 1, 6, 12, 6), 1, 0, 5),
 (229, 'HaAm15937', 'HaAm15937224', datetime.datetime(2021, 1, 6, 12, 22), 2, 24, 36),
 (230, 'HaDe16565', 'HaDe16565224', datetime.datetime(2021, 1, 6, 12, 23), 1, 0, 32),
 (231, 'HaSe20883', 'HaSe20883224', datetime.datetime(2021, 1, 6, 12, 33), 1, 0, 32),
 (232, 'KiMr25211', 'KiMr25211224', datetime.datetime(2021, 1, 6, 12, 34), 3, 110, 3),
 (233, 'SoRu37469', 'SoRu37469224', datetime.datetime(2021, 1, 6, 12, 36), 1, 0, 5),

In [140]:
%%sql
SELECT DAYNAME(time_of_record) AS Day_of_the_week, 
AVG(time_in_queue) AS Avg_queue_time
FROM visits
GROUP BY DAYNAME(time_of_record);

 * mysql+pymysql://root:***@localhost:3306/md_water_services
7 rows affected.

[('Friday', Decimal('52.7397')),
 ('Saturday', Decimal('246.2941')),
 ('Sunday', Decimal('81.5294')),
 ('Monday', Decimal('59.6780')),
 ('Tuesday', Decimal('47.0795')),
 ('Wednesday', Decimal('42.5434')),
 ('Thursday', Decimal('46.0164'))]

In [145]:
%%sql
SELECT HOUR(time_of_record) AS Hour_per_day,
ROUND(AVG(time_in_queue)) AS Avg_queue_time
FROM visits
GROUP BY HOUR(time_of_record)
ORDER BY Hour_per_day DESC;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
14 rows affected.

[(19, Decimal('168')),
 (18, Decimal('147')),
 (17, Decimal('149')),
 (16, Decimal('47')),
 (15, Decimal('48')),
 (14, Decimal('47')),
 (13, Decimal('47')),
 (12, Decimal('47')),
 (11, Decimal('46')),
 (10, Decimal('48')),
 (9, Decimal('49')),
 (8, Decimal('149')),
 (7, Decimal('149')),
 (6, Decimal('149'))]

In [152]:
%%sql
SELECT
TIME_FORMAT(TIME(time_of_record), '%H:00') AS hour_of_day,
ROUND(AVG(time_in_queue)) AS Avg_queue_time
FROM visits
GROUP BY TIME_FORMAT(TIME(time_of_record), '%H:00')
;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
14 rows affected.

[('09:00', Decimal('49')),
 ('10:00', Decimal('48')),
 ('11:00', Decimal('46')),
 ('12:00', Decimal('47')),
 ('13:00', Decimal('47')),
 ('14:00', Decimal('47')),
 ('15:00', Decimal('48')),
 ('16:00', Decimal('47')),
 ('07:00', Decimal('149')),
 ('18:00', Decimal('147')),
 ('08:00', Decimal('149')),
 ('17:00', Decimal('149')),
 ('06:00', Decimal('149')),
 ('19:00', Decimal('168'))]

In [154]:
%%sql
SELECT
TIME_FORMAT(TIME(time_of_record), '%H:00') AS hour_of_day,
DAYNAME(time_of_record),
CASE
WHEN DAYNAME(time_of_record) = 'Sunday' THEN time_in_queue
ELSE NULL
END AS Sunday
FROM
visits
WHERE
time_in_queue != 0
LIMIT 100;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
100 rows affected.

[('09:00', 'Friday', None),
 ('09:00', 'Friday', None),
 ('10:00', 'Friday', None),
 ('10:00', 'Friday', None),
 ('11:00', 'Friday', None),
 ('11:00', 'Friday', None),
 ('12:00', 'Friday', None),
 ('12:00', 'Friday', None),
 ('13:00', 'Friday', None),
 ('13:00', 'Friday', None),
 ('13:00', 'Friday', None),
 ('14:00', 'Friday', None),
 ('14:00', 'Friday', None),
 ('15:00', 'Friday', None),
 ('16:00', 'Friday', None),
 ('07:00', 'Saturday', None),
 ('07:00', 'Saturday', None),
 ('09:00', 'Saturday', None),
 ('11:00', 'Saturday', None),
 ('13:00', 'Saturday', None),
 ('09:00', 'Sunday', 103),
 ('11:00', 'Sunday', 39),
 ('12:00', 'Sunday', 112),
 ('14:00', 'Sunday', 30),
 ('14:00', 'Sunday', 104),
 ('07:00', 'Monday', None),
 ('09:00', 'Monday', None),
 ('11:00', 'Monday', None),
 ('11:00', 'Monday', None),
 ('12:00', 'Monday', None),
 ('12:00', 'Monday', None),
 ('14:00', 'Monday', None),
 ('14:00', 'Monday', None),
 ('15:00', 'Monday', None),
 ('15:00', 'Monday', None),
 ('16:00', 'Monday', None),
 ('16:00', 'Monday', None),
 ('18:00', 'Monday', None),
 ('07:00', 'Tuesday', None),
 ('08:00', 'Tuesday', None),
 ('09:00', 'Tuesday', None),
 ('09:00', 'Tuesday', None),
 ('10:00', 'Tuesday', None),
 ('10:00', 'Tuesday', None),
 ('10:00', 'Tuesday', None),
 ('10:00', 'Tuesday', None),
 ('11:00', 'Tuesday', None),
 ('12:00', 'Tuesday', None),
 ('13:00', 'Tuesday', None),
 ('13:00', 'Tuesday', None),
 ('13:00', 'Tuesday', None),
 ('14:00', 'Tuesday', None),
 ('14:00', 'Tuesday', None),
 ('15:00', 'Tuesday', None),
 ('16:00', 'Tuesday', None),
 ('16:00', 'Tuesday', None),
 ('16:00', 'Tuesday', None),
 ('16:00', 'Tuesday', None),
 ('17:00', 'Tuesday', None),
 ('06:00', 'Wednesday', None),
 ('07:00', 'Wednesday', None),
 ('09:00', 'Wednesday', None),
 ('09:00', 'Wednesday', None),
 ('09:00', 'Wednesday', None),
 ('09:00', 'Wednesday', None),
 ('10:00', 'Wednesday', None),
 ('10:00', 'Wednesday', None),
 ('10:00', 'Wednesday', None),
 ('10:00', 'Wednesday', None),
 ('11:00', 'Wednesday', None),
 ('11:00', 'Wednesday', None),
 ('12:00', 'Wednesday', None),
 ('12:00', 'Wednesday', None),
 ('12:00', 'Wednesday', None),
 ('13:00', 'Wednesday', None),
 ('14:00', 'Wednesday', None),
 ('14:00', 'Wednesday', None),
 ('14:00', 'Wednesday', None),
 ('15:00', 'Wednesday', None),
 ('15:00', 'Wednesday', None),
 ('15:00', 'Wednesday', None),
 ('15:00', 'Wednesday', None),
 ('15:00', 'Wednesday', None),
 ('15:00', 'Wednesday', None),
 ('16:00', 'Wednesday', None),
 ('18:00', 'Wednesday', None),
 ('06:00', 'Thursday', None),
 ('07:00', 'Thursday', None),
 ('07:00', 'Thursday', None),
 ('07:00', 'Thursday', None),
 ('08:00', 'Thursday', None),
 ('09:00', 'Thursday', None),
 ('09:00', 'Thursday', None),
 ('10:00', 'Thursday', None),
 ('10:00', 'Thursday', None),
 ('11:00', 'Thursday', None),
 ('12:00', 'Thursday', None),
 ('12:00', 'Thursday', None),
 ('12:00', 'Thursday', None),
 ('12:00', 'Thursday', None)]

In [159]:
%%sql
SELECT
TIME_FORMAT(TIME(time_of_record), '%H:00') AS hour_of_day,

ROUND(AVG(
CASE
WHEN DAYNAME(time_of_record) = 'Sunday' THEN time_in_queue
ELSE NULL
END
),0) AS Sunday,

ROUND(AVG(
CASE
WHEN DAYNAME(time_of_record) = 'Monday' THEN time_in_queue
ELSE NULL
END
),0) AS Monday,

ROUND(AVG(
CASE
WHEN DAYNAME(time_of_record) = 'Tuesday' THEN time_in_queue
ELSE NULL
END
),0) AS Tuesday,

ROUND(AVG(
CASE
WHEN DAYNAME(time_of_record) = 'Wednesday' THEN time_in_queue
ELSE NULL
END
),0) AS Wednesday,

ROUND(AVG(
CASE
WHEN DAYNAME(time_of_record) = 'Thursday' THEN time_in_queue
ELSE NULL
END
),0) AS Thursday,

ROUND(AVG(
CASE
WHEN DAYNAME(time_of_record) = 'Friday' THEN time_in_queue
ELSE NULL
END
),0) AS Friday,

ROUND(AVG(
CASE
WHEN DAYNAME(time_of_record) = 'Saturday' THEN time_in_queue
ELSE NULL
END
),0) AS Saturday

FROM
visits
WHERE
time_in_queue != 0 
GROUP BY
hour_of_day
ORDER BY
hour_of_day;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
14 rows affected.

[('06:00', Decimal('79'), Decimal('190'), Decimal('134'), Decimal('112'), Decimal('134'), Decimal('153'), Decimal('247')),
 ('07:00', Decimal('82'), Decimal('186'), Decimal('128'), Decimal('111'), Decimal('139'), Decimal('156'), Decimal('247')),
 ('08:00', Decimal('86'), Decimal('183'), Decimal('130'), Decimal('119'), Decimal('129'), Decimal('153'), Decimal('247')),
 ('09:00', Decimal('84'), Decimal('127'), Decimal('105'), Decimal('94'), Decimal('99'), Decimal('107'), Decimal('252')),
 ('10:00', Decimal('83'), Decimal('119'), Decimal('99'), Decimal('89'), Decimal('95'), Decimal('112'), Decimal('259')),
 ('11:00', Decimal('78'), Decimal('115'), Decimal('102'), Decimal('86'), Decimal('99'), Decimal('104'), Decimal('236')),
 ('12:00', Decimal('78'), Decimal('115'), Decimal('97'), Decimal('88'), Decimal('96'), Decimal('109'), Decimal('239')),
 ('13:00', Decimal('81'), Decimal('122'), Decimal('97'), Decimal('98'), Decimal('101'), Decimal('115'), Decimal('242')),
 ('14:00', Decimal('83'), Decimal('127'), Decimal('104'), Decimal('92'), Decimal('96'), Decimal('110'), Decimal('244')),
 ('15:00', Decimal('83'), Decimal('126'), Decimal('104'), Decimal('88'), Decimal('92'), Decimal('110'), Decimal('248')),
 ('16:00', Decimal('83'), Decimal('127'), Decimal('99'), Decimal('90'), Decimal('99'), Decimal('109'), Decimal('251')),
 ('17:00', Decimal('79'), Decimal('181'), Decimal('135'), Decimal('121'), Decimal('129'), Decimal('151'), Decimal('251')),
 ('18:00', Decimal('80'), Decimal('174'), Decimal('122'), Decimal('113'), Decimal('132'), Decimal('158'), Decimal('240')),
 ('19:00', Decimal('127'), Decimal('159'), Decimal('145'), Decimal('176'), Decimal('137'), Decimal('103'), Decimal('282'))]

In [183]:
%%sql
SELECT
type_of_water_source,
SUM(number_of_people_served) AS population_served
FROM
water_source
GROUP BY
type_of_water_source
ORDER BY
population_served DESC;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
5 rows affected.

[('shared_tap', Decimal('11945272')),
 ('well', Decimal('4841724')),
 ('tap_in_home', Decimal('4678880')),
 ('tap_in_home_broken', Decimal('3799720')),
 ('river', Decimal('2362544'))]

In [6]:
%%sql
SELECT *
FROM visits
LIMIT 5;

 * mysql+pymysql://root:***@localhost:3306/md_water_services
5 rows affected.

[(0, 'SoIl32582', 'SoIl32582224', datetime.datetime(2021, 1, 1, 9, 10), 1, 15, 12),
 (1, 'KiRu28935', 'KiRu28935224', datetime.datetime(2021, 1, 1, 9, 17), 1, 0, 46),
 (2, 'HaRu19752', 'HaRu19752224', datetime.datetime(2021, 1, 1, 9, 36), 1, 62, 40),
 (3, 'AkLu01628', 'AkLu01628224', datetime.datetime(2021, 1, 1, 9, 53), 1, 0, 1),
 (4, 'AkRu03357', 'AkRu03357224', datetime.datetime(2021, 1, 1, 10, 11), 1, 28, 14)]